### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by bukhsh** [AntaresSimulatorTeam/Antares_Simulator#1]
Hi I am trying to install this on Ubuntu but coming across an error that I do not understand. Could you please help me with this. I have attached cmake log files.

[CMakeError.log](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/2286631/CMakeError.log)
[CMakeOutput.log](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/2286632/CMakeOutput.log)

Also, I believe in the INSTALL.txt file: section 3.2.1. should be :

$ cd ${ANTARES}/src/

**Comment by jalazawa** [comment]
It seems you don't have "lpthreads"

```C
/usr/bin/x86_64-linux-gnu-ld: cannot find -lpthreads
```

Try to install it with help from [here](https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads)

After this, Can you send a new "CMakeError.log", please ?

**Comment by jmkerloch** [comment]
Issue closed  with new CMake build chain.
Please post a new issue if needed.
