### ISSUE TITLE
Output variables : change  endHour and weekBegin prototype

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1021]
**endHour** and **weekBegin** are results post treatment functions possibly used by an output variable.
These method have a default definition in base class **IVariable**.
Actually there are only one variable that re-defines them : **BindingConstMarginCost**.
This re-definitions impies an access to the **numSapce**, obtained through the **State** object passed as argument.
In order to be consistent with the rest of the code, we need to add **numSapce** in the list of arguments of these functions, and 
remove **numSapce** from the data members of **State**.

**Comment by flomnes** [comment]
### hourEnd
`hourInTheYear` and `state.eensSystemCN` are used for the adequacy-draft output variables.

For binding constraints, it is used as follows for `state.problemeHebdo->ResultatsContraintesCouplantes`, but `hourInTheYear` isn't used.

Once adq-draft is removed, we can remove argument `hourInTheYear`. But state will have to stay.

### weekBegin
Here as well, `state` is used for `state.problemeHebdo->ResultatsContraintesCouplantes[bindConstraintGlobalNumber_]` and `state.numSpace` binding constraints.

Pretty much same conclusion here: `state` may have to stay for now.
