### ISSUE TITLE
Remove sequence <year>-<week> in variables.txt

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1052]
Files **variables-\<year\>-\<week\>.txt** are only useful for **Xpansion**.
They contains duplicated data over a year.
Only the last piece of data of each line (the time step = hour in the year) is different from a file to another.
This piece of data can be recreated in memory by **Xpansion**, so that it needs only one file **variables.txt**.
Remove the time step from each line and make **Antares Simulator** generate only one file per year.

**Comment by flomnes** [comment]
@a-zakir @tbittar If variables were named in the MPS files, could we get rid of `variables.txt` files completely ?

**Comment by tbittar** [comment]
> @a-zakir @tbittar If variables were named in the MPS files, could we get rid of `variables.txt` files completely ?

Yes I agree, the `variables.txt` file is only used in Xpansion to map the id of the variables to their names.

**Comment by flomnes** [comment]
Then I suggest

- Naming variables & constraints in MPS files
- Removing files `variables.txt`

All at the same time.
