### ISSUE TITLE
OR-Tools : glop solver use fail with many examples

### ISSUE THREAD

**Issue by jmkerloch** [AntaresSimulatorTeam/Antares_Simulator#106]
Problem resolution fail when using OR-Tools glop solver with many examples.

Here is an very simple example :
[Valid-800-RC1.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/5809014/Valid-800-RC1.zip)

**Comment by jmkerloch** [comment]
Before further investigation, GLOP solver must be deactivated from antares-solver.

**Comment by sgatto** [comment]
Glop seems to be currently unable to solve some Antares problems.
We decide to deactivate the possibility to use GLOP as solver.
