### ISSUE TITLE
Remove obsolete mode 'adequacy draft'

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1060]
TODO
- [ ] List all code where mode "adequacy draft" is present
- [ ] Estimate how much time required to remove this code

**Comment by payetvin** [comment]
The source code is contained in
- src/solver/variable/adequacy-draft/*
- src/solver/simulation/adequacy-draft.cpp 
- src/solver/simulation/adequacy-draft.h 
- src/solver/main/adequacy-draft.cpp

It'll be easy to delete
The code is then mostly called in
- src/solver/variable/
- src/solver/simulation/ 
- src/libs/antares/study/
- ui/simulator/windows/

I think removing the adequacy draft mode would not take too much time
