### ISSUE TITLE
Avoid computing annual aggregation results when output not asked 

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1072]
For some studies, It takes a few seconds (between 3 and 10 seconds, more often 4) per year to build annual results by aggregation regarding the **binding constraints** results :
- when the study contains many **BC**s .
- when user deactivate the output of marginal costs on BCs

So this overhead is not a big deal.
However, we should still consider not computing these results at any time intervals when marginal costs on **BC**s is not asked by user.

This works a well for any other output variables.

**Comment by pet-mit** [comment]
ANT-2173
