### ISSUE TITLE
Resolution with OR-Tools+XPRESS significantly longer than Sirius

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1089]
### BP21 : Total times with the  "v8.4.2-release" asset

1000 MCY
Sirius : 11317s
XPRESS : 16711s

### BP21

2 MCY, using callgrind

```bash
valgrind --tool=callgrind --callgrind-out-file=ortools_sirius.callgrind $SOLVER840 --use-ortools --ortools-solver sirius BP21
```

[benchmark.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/10424227/benchmark.zip)

**Comment by flomnes** [comment]
This seems to be related to the machine used. Further investigation is required.

**Comment by payetvin** [comment]
Fixed
