### ISSUE TITLE
Remove global variables

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1119]
**Description**

The presence of global variables and singletons has major drawbacks:
- it makes more or less impossible the use of the solver as a lib, because the user will get bugs when running multiple simulations, at least in parallel, and maybe also in sequence
- it hurts understandability of the code, because functions don't tell correctly their inputs and outputs
- it makes very hard unit testing, for the same reason

Therefore, removing those globale variables is a must-do.
The culprits are:
- `gGlobalCurrentStudy` in `current.cpp`
- all variables related to Monte Carlo draws in `sim_extern_variables_globales.h`

**Implementation**

All those variables must be explicitly provided to functions using them (relevance of including them in existing classes needs to be assessed).

**Comment by flomnes** [comment]
There are still global variables, unfortunately

**Comment by sylvlecl** [comment]
For remaining variables in MC draws in `sim_extern_variables_globales.h`, we need to create a class containing all draws, instead of the differents independant vectors.

That object must be created by method `InitializeTimeSeriesNumbers_And_ThermalClusterProductionCost`, and then be passed through to functions that need them.
