### ISSUE TITLE
Refactor src/solver/optimisation

### ISSUE THREAD

**Issue by payetvin** [AntaresSimulatorTeam/Antares_Simulator#1127]
Need to refactor all files in src/solver/optimisation

Most of the variables are declared at the start of functions, even those used in loops and are reused several times -> bad practice
The "var" variable is used for anything, loops or temporary values, change name to i or j for loops and suitable name for other uses.
Some var assigns are useless (see opt_calcul_des_pmin_MUT_MDT.cpp line 190)

Probably several other issues

**Comment by sylvlecl** [comment]
I also suspect there is a lot of code repetition in the various for loops.

There is at least some functions to create to re-use code, and probably some operations could be better formulated as matrix/or vector operations.
