### ISSUE TITLE
Parameters : split parameters.cpp in several pieces

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1131]
**parameters.h/.cpp** and **fwd.h** are growing bigger and bigger.
We should split them into finer grained files which could be called **some-subject-params.h/.cpp**.
Note that definitions of **enum**  could be moved to **some-subject-params.h** : see if this implies a lot of work or not

### Themes
- [ ] Adequacy patch, see #1154
- [ ] Random seeds (`seed[seedMax]`, `resetSeeds`)
- [ ] Hydro (heuristic policy, pricing mode, initial reservoir level, hydro debug)
- [ ] Timeseries (number of timeseries, ~~refresh interval~~)
- [ ] Simulation mode (economy/adequacy/expansion
- [ ] Playlist / `yearsFilter` / section "playlist"
- [ ] Years weights (search for "weight", 4-5 results)
- [ ] TS generation (intra-modal / inter-modal, refresh intervals, `storeTimeseriesNumbers`, `timeSeriesAccuracyOnCorrelation`)
- [ ] `variablesPrintInfo` / section "variables selection"
- [ ] OR-Tools (ON/OFF, what solver to use)
- [ ] Scenario builder (`activeRulesScenario`, `useCustomScenario`)
- [ ] Calendar (`simulationDays`, `dayOfThe1stJanuary`, `firstWeekday`, `firstMonthInYear`, `leapYear`
- [ ] Result export (`yearByYear`, `synthesis`, `noOutput`, `resultFormat`)

### When using parameters
Instead of passing `parameters`, pass only the required part, e.g `parameters.adqPatchParams`, `parameters.hydroParams`, etc.

**Comment by flomnes** [comment]
### Themes
- Random seeds
- Hydro (heuristic policy, pricing mode, initial reservoir level, hydro debug)
- Timeseries (number of timeseries, refresh interval)
- Playlist / `yearsFilter` / section "playlist"
- `variablesPrintInfo` / section "variables selection"
- OR-Tools (ON/OFF, solver)
- Scenario builder (`activeRulesScenario`, `useCustomScenario`)
- Calendar (`simulationDays`, `dayOfThe1stJanuary`, `firstWeekday`, `firstMonthInYear`, `leapYear`
- Result export (`yearByYear`, `synthesis`, `noOutput`, `resultFormat`)
