### ISSUE TITLE
Add simulation.start and simulation.end in execution_info.ini

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/Antares_Simulator#1148]
**Description**
execution_info.ini file should contain simulation.start and simulation.end info (that are in generaldata.ini) as there are important to predict how long the study will take. It should belong to the [study] tag.

**Screenshots and additional files**
![pb_ini](https://user-images.githubusercontent.com/102529366/216067673-62b3c3c7-9302-406f-9aaa-3646ad39bbe2.png)

**OS and version**
 - OS: [e.g. Windows, GNU/Linux]
 - Antares Simulator version: Starting at 8.3.1 version (before execution_info.ini file did not existed)

**Comment by flomnes** [comment]
I suggest adding only `simulation.end - simulation.start`, would that work as well ?

**Comment by guilpier-code** [comment]
Hello @MartinBelthle, note that this information is available in : 
**<your-study>/output/yyyymmdd-hhmmeco/about-the-study/parameters.ini**
Also note that this file is a copy of the  **generaldata.ini** that was used to run your simulation.

That said, maybe you need to have this information in the **execution_info.ini** for any purpose.

**Comment by MartinBelthle** [comment]
Currently AntaresWeb uses the **execution_info.ini** to gather information on a JobResult. I imagine this is because study inputs can be modified so does the **generaldata.ini** but not its outputs that refer to a specific job. Maybe AntaresWeb should read the information in the **about-the-study/parameters.ini**  and in that case this issue is not relevant anymore, i will discuss this with the team.

**Comment by payetvin** [comment]
@MartinBelthle is it still needed ?

**Comment by payetvin** [comment]
Not relevant anymore
