### ISSUE TITLE
Thermal production exceeds the availability for some hours

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1151]
**Description**
Cluster with a single unit
- Pnom = 1650 MW
- Pmin = 924 MW (= 56% Pmax)
- Max_h(Thermal availability[h]) = 1674 MW for that year
- Spinning reserve = 2%
- Unit Commitment mode = fast

For a given hour, the generated power exceeds the availability (1848 MW).

**Expected behavior**
Generated power should not exceed the thermal availability.

**Screenshots and additional files**
ETUDE_23

**OS and version**
 - OS: Windows 10
 - Antares Simulator version: 8.2.3 

**Additional context**
Reporter : TLA

**Comment by flomnes** [comment]
Confirmed on 8.4.2 (latest stable version), both in **fast** and **accurate** Unit commitment mode.

**Comment by flomnes** [comment]
### Observations on a simplified study (1 area)

| Pmin (MW) | Result |
|---|---|
| 0 | The production is always equal to 0, except for some timesteps (477, 1577, etc.) |
| 400 | The production is constant, equal to 800MW |
| 700 | The production is constant, equal to 1400MW |
| 924 | The production is constant, equal to 1674MW |
| 1600 | The production is constant, equal to 3200MW |

It seems that the min generation that we use is not Pmin, but rather 2*Pmin. This behavior is incorrect.

**Comment by flomnes** [comment]
### Investigation of MPS files on a simplified study (1 area)
I added some logs to determine the `index -> name` mapping. The faulty cluster is indexed as 8.
```
[Fri Feb  3 09:19:39 2023][solver][notic] Palier = 8 FR_REDACTED
```
File **variables-1-1.txt** then allows us to determine the production variable for that cluster for every `t=1..168`.

```
8 PalierThermique 0 8 0
9 PalierThermique 0 9 0
...
28 PalierThermique 0 8 1
...
48 PalierThermique 0 8 2 
```

I enabled MPS for both optimizations. Keeping Pmax=1663MW and Pmin=1600MW.

**problem-1-1--optim-nb-1.mps**
```
 UP BNDVALUE  C0000008  3200.000000000
```

**problem-1-1--optim-nb-2.mps**
```
 LO BNDVALUE  C0000008  3200.000000000
 UP BNDVALUE  C0000008  3200.000000000
```

- For the 1st optimization, Xmin[0]=0 (implicit), Xmax[0]=3200
- For the 2nd optimization, Xmin[0]=Xmax[0]=3200

The same applies for all time-steps.

_Note : Xmin[0] is the lower-bound for the 1st time-step for t=1, and so on._

**Conclusion**: Bounds for thermal production variables are incorrect for this cluster.

**Comment by flomnes** [comment]
### Debugging session
File **src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp** (thermal heuristic between the 2 weekly optimizations)
Add some logs
```cpp
for (int Pdt = 0; Pdt < NombreDePasDeTemps; Pdt++)
{
    if (PminDuPalierThermiquePendantUneHeure[Palier] * NbGrpOpt[Pdt]
        > PuissanceMinDuPalierThermique[Pdt])
    {
        PuissanceMinDuPalierThermique[Pdt]
          = PminDuPalierThermiquePendantUneHeure[Palier] * NbGrpOpt[Pdt];
        logs.notice() << "UP " << Palier << "," <<
          Pdt <<
          " PuissanceMinDuPalierThermique[Pdt] = " << PuissanceMinDuPalierThermique[Pdt] <<
          " PminDuPalierThermiquePendantUneHeure[Palier] = " << PminDuPalierThermiquePendantUneHeure[Palier] <<
          " NbGrpOpt[Pdt] = " << NbGrpOpt[Pdt];
    }

    if (PuissanceMinDuPalierThermique[Pdt] > PuissanceDisponibleDuPalierThermique[Pdt])
    {
        PuissanceMinDuPalierThermique[Pdt] = PuissanceDisponibleDuPalierThermique[Pdt];
        logs.notice() << "DOWN " << Palier << "," << Pdt << " "<< PuissanceMinDuPalierThermique[Pdt];
    }
}
```

It appears that 2 units are considered, instead of a single one
```
[Fri Feb  3 10:44:23 2023][solver][notic] UP 8,0 PuissanceMinDuPalierThermique[Pdt] = 3200.000000 PminDuPalierThermiquePendantUneHeure[Palier] = 1600.000000 NbGrpOpt[Pdt] = 2
[Fri Feb  3 10:44:23 2023][solver][notic] UP 8,1 PuissanceMinDuPalierThermique[Pdt] = 3200.000000 PminDuPalierThermiquePendantUneHeure[Palier] = 1600.000000 NbGrpOpt[Pdt] = 2
[Fri Feb  3 10:44:23 2023][solver][notic] UP 8,2 PuissanceMinDuPalierThermique[Pdt] = 3200.000000 PminDuPalierThermiquePendantUneHeure[Palier] = 1600.000000 NbGrpOpt[Pdt] = 2
[Fri Feb  3 10:44:23 2023][solver][notic] UP 8,3 PuissanceMinDuPalierThermique[Pdt] = 3200.000000 PminDuPalierThermiquePendantUneHeure[Palier] = 1600.000000 NbGrpOpt[Pdt] = 2
```

It also appears that since `PuissanceDisponibleDuPalierThermique[Pdt]=3200`, the Pmin isn't corrected as a 2nd step (2nd if).

Two things are wrong at this point:
- The heuristic gives 2 units, although only one exists `NbGrpOpt[Pdt] = 2`
- The Pmax should be 1663, but it's 3200.

**Comment by flomnes** [comment]
### Probable cause
The availability for some time-steps (1663MW) is greater than the nominal capacity (1650MW).

```cpp
double P = ProductionThermiqueOptimale[Pdt]->ProductionThermiqueDuPalier[Palier];  
NbGrpCourbeGuide[Pdt] = (int)ceil(P / TailleUnitaireDUnGroupeDuPalierThermique[Palier]);
```

Indeed, increasing the nominal capacity to 1700MW fixes the issue. Optimization problems now have the appropriate Xmin & Xmax, and simulation results are consistent with user input.

**problem-1-1--optim-nb-1.mps**
```
 UP BNDVALUE  C0000008  1663.000000000
```
**problem-1-1--optim-nb-2.mps**
```
 LO BNDVALUE  C0000008  1600.000000000
 UP BNDVALUE  C0000008  1663.000000000
```

![image](https://user-images.githubusercontent.com/26088210/216576339-749556f3-4b6a-4428-a234-87c06e39c8d2.png)

**Comment by PPlessiez** [comment]
A question for you @flomnes : 
I know that Antares sometimes applies a pre-treatment on the available capacity of thermal clusters to match it with the Pnom of the cluster. Below is an example from the logs of a study:
_Area : FR cluster name : FR_Nuclear_n4 available power lifted to match Pmin and Pnom requirements_

Is this treatment still implemented? If so, shouldn't it have treated the issue?

**Comment by flomnes** [comment]
> Is this treatment still implemented? If so, shouldn't it have treated the issue?

Indeed ! From the original logs
```
[Thu Feb  2 11:31:37 2023][solver][warns] Area : FR cluster name : FR_REDACTED available power lifted to match Pmin and Pnom requirements
```
This pre-processing is done here

https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/0df2f76d1cfce4cb62b62fddbb52b37bc1528219/src/solver/application.cpp#L143-L183

In other words,
```cpp
if (cluster.nominalCapacityWithSpinning < cluster.minStablePower)
    PminDUnGroupeDuPalierThermique = cluster.nominalCapacityWithSpinning;
else
    PminDUnGroupeDuPalierThermique = cluster.minStablePower;

// For every x < width (TS index), y < height (hour index)
if (PminDUnGroupeDuPalierThermique * ceil(cluster.series->series.entry[x][y] / cluster.nominalCapacityWithSpinning) > cluster.series->series.entry[x][y])
{
    // warning, change coefficient cluster.series->series.entry[x][y]
    // Old value 1629.740000, new value 1848.000000
}
```

**Comment by PPlessiez** [comment]
Ok, so it seems that you have two treatments:
- The Pmin of a unit is the minimum between the value filled in by the user and the nominal capacity of a unit including spining.
- If you can't turn on all your units at Pmin because the availability is unsufficient, then you adjust the availability so you can have all your units at Pmin.

But it seems it doesn't do anything special if the availability is higher than the nominal capacity of the whole cluster, which explains why the issue was encountered.

**Comment by flomnes** [comment]
> Ok, so it seems that you have two treatments:
> 
> - The Pmin of a unit is the minimum between the value filled in by the user and the nominal capacity of a unit including spining.
> 

The Pmin here is just a temporary variable, the value is discarded afterwards.

> - If you can't turn on all your units at Pmin because the availability is unsufficient, then you adjust the availability so you can have all your units at Pmin.
> 
> 

Sorry if it wasn't clear, but from the code, the thermal availability timeseries are uplifted. Not the other characteristics (Pmin, Pnom)
> 
> But it seems it doesn't do anything special if the availability is higher than the nominal capacity of the whole cluster, which explains why the issue was encountered.

The thermal heuristic seems to be doing fine. Changing user data is dangerous, maybe this should be an error. As a side note, I suggest moving these checks and some others to AntaREST. This would greatly improve user experience because fewer launches would fail (to be discussed).
