### ISSUE TITLE
Definition of antares-solver behavior for study with different antares version

### ISSUE THREAD

**Issue by jmkerloch** [AntaresSimulatorTeam/Antares_Simulator#117]
When using _antares-8.0-solver_ with _antaresXpansion_ it appears that previous antares study can be used with a new version of antares.

This differs from _antares-simulator_ behavior which require a study upgrade before any simulation.

We must define the behavior of _antares-solver_ : 
- reject any study with a different version ?
- auto upgrade of study with a different version ?
- allow use of previous study if parameters are compatible ? (current behaviour) 

### Decision
After further discussions the behaviour to be retained is :
- _antares-solver_ should exit when the study-version differs from the solver-version  except for the last number (x) V.v.x

**Comment by sgatto** [comment]
I discussed with @MDoquet , he validated a change in the behaviour:
 if the study-version differs from the solver-version Antares should
tell the user about the problem and stop

**Comment by jmkerloch** [comment]
There is an issue with getting the last number of vx.y.z (8.0.0 for example).
There is no indication of z value in study attribute `StudyHeader` only a enum defining version  refering to _libs/antares/study/version.h_ : 

```
typedef enum // Version
	{
		//! Unknown version of a study
		versionUnknown = 0,
		//! The old 1.x Study version
		version1xx = 100,
		//! Study version: 2.0
		version200 = 200,
		//! Study Version 2.1
		version210 = 210,
...
		//! Study version 7.1
		version710 = 710,
		//! Study version 7.2
		version720 = 720,
		//! Study version 8.0
		version800 = 800,

		// see versionLatest below

		// Constants
		//! A more recent version that we can't handle
		versionFutur = 99999,

	}  Version;
```

We can only compare if study is above or equal to latest enum value : 

```
if (pStudy->header.version < Data::versionLatest)
{
  logs.error() << "The study must be upgraded to the v"
	  << Data::VersionToCStr((Data::Version)Data::versionLatest)
	  << " format before launching the solver";
  return false;
}
```

**Comment by jmkerloch** [comment]
We could define a enum `Data::versionLatestMinor` defining latest minor version.

We will compare to this value instead of `Data::VersionLatest`.

**Comment by flomnes** [comment]
Retro-compatibility is fully supported until study version 7.0. There is no plans to remove this compatibility.
