### ISSUE TITLE
Refactor src/solver/optimisation

### ISSUE THREAD

**Issue by payetvin** [AntaresSimulatorTeam/Antares_Simulator#1176]
Following to https://github.com/AntaresSimulatorTeam/Antares_Simulator/issues/1127 and https://github.com/AntaresSimulatorTeam/Antares_Simulator/issues/1161

Too long functions (1000 lines for OPT_ConstruireLaMatriceDesContraintesDuProblemeQuadratique)

_**for loops**_ on common things could be divided in function  

The following pattern is used in nearly every file and must be add in a function: 
```        
if (var >= 0)
{
    Pi[nombreDeTermes] = -1.0;
    Colonne[nombreDeTermes] = var;
    nombreDeTermes++;
}
```

**Comment by a-zakir** [comment]
Fait #1627
