### ISSUE TITLE
Xpansion : mode expansion dry

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#120]
**Contexte** : le mode expansion standard permet d’une part de limiter l’optimisation (journalière/hebdomadaire) à la première phase de résolution (relaxée) , d’imprimer les résultats correspondants ainsi qu’un fichier contenant la valeur de la fonction objectif trouvée après avoir résolu le problème. Ce mode de simulation peut rester utile à l’avenir, en revanche les travaux actuels sur un nouveau module d’étude des investissements appellent le développement de deux modes supplémentaires « expansion-dry » et « expansion-verbose ». Ce ticket décrit les traitements associés au mode « expansion-dry ».
Le mode « expansion-verbose » est décrit dans le ticket #126.

Le mode Expansion dry se caractérise par le fait que :
- Le niveau de démarrage de chaque journée/semaine d’optimisation  n est le niveau heuristique trouvé pour le premier jour de la période lors des optimisations hydrauliques préliminaires  (en lieu et place d’un niveau de démarrage de la semaine égal au niveau final de la semaine   précédente).
- Le/les  problèmes mps associés aux journées/semaines d’optimisation sont imprimés
- Un code de nommage des variables et des contraintes manipulées par le module d’investissements est appelé (code « lpnamer ») et un fichier de références symboliques (unique pour toute la simulation) est imprimé lord de la construction du problème d’optimisation (section « opt »)   
- La résolution des problèmes n’est pas faite par Antares (le solveur n’est pas appelé) et aucun résultat de simulation n’est imprimé.

**Comment by flomnes** [comment]
1st & 4rd points unresolved for now. 2nd & 3nd done
