### ISSUE TITLE
Short term storage : refactor the OPT part  

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1205]
As an example, function **OPT_InitialiserLesBornesDesVariablesDuProblemeLineaire(...)** and the source file it belongs to are growing.
A possible quite simple solution for them to stop growing would be to have : 
```C++
void OPT_InitialiserLesBornesDesVariablesDuProblemeLineaire(PROBLEME_HEBDO* problemeHebdo, ...)
{
      problemeHebdo->hydroModeller.giveBoundsToOptVariables();
      problemeHebdo->thermalModeller.giveBoundsToOptVariables();
      ...
      // And of course
      problemeHebdo->shortTermStorageModeller.giveBoundsToOptVariables();
      ...
}
```
Several remarks about this :
- This solution should be better than what we have now : the current **OPT** code forces us to make functions grow and do much more things than they should.
- It intends to extract bound settings in a more specialized class, called for instance **ShortTermstorageModeller**.
- This solution would be applicable to any other functions in the **OPT** part. This means, for example that the **ShortTermstorageModeller** would have a public member function **addConstraintsToProblem()**
- It would be applicable to any other production asset taking a part in the optimization 
- Class **ShortTermstorageModeller** would have a constructor taking as argument  a **PROBLEME_HEBDO** and characteristics on short term storage.
- Doing this for every production asset and every **OPT** function should eventually lead to simplify the code a lot : for instance, we could eventually have : 
```C++
 // Only when setting bounds here, but could be applied to any optimization preparation stage
void OPT_InitialiserLesBornesDesVariablesDuProblemeLineaire(ProductionAssetList & list_of_assets)
{
    for (auto* asset : list_of_assets)
        asset->giveBoundsToOptVariables();
}
```

**Comment by pet-mit** [comment]
ANT-2187
