### ISSUE TITLE
Use constants instead of misused anonymous enums  

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1212]
In many parts of the code, we use enums where we shoud use constants. See in particular in the `variable` module:

https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/96832a3a7f75534b5cb68ab7f62421a729acfb51/src/solver/variable/area.h#L60-L74

**Comment by payetvin** [comment]
dup of #1211
