### ISSUE TITLE
Remove hourForClusters functions

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1221]
In output generation part of **Antares Simulator**, we have currently functions **hourForClusters(...)** in output variable classes.
These functions are meant to handle clusters of any kinds (thermal, renewable and ST storage) in output reports.
This functions are defined either in   : 
- parent class **IVariable** by default (and do nothing)
- or in some child classes where we need them to retrieve some results on clusters from weekly simulation.

It seems these functions are not strictly necessary as their content can be moved to functions **hourForEachArea(...)**.
So we should study the possibility to do this.

Note that this work implies to make changes in **src/solver/variable/area.inc.hxx : hourForEachArea(...)**, and more precisely to swap the calls to : 
```C++
variablesForArea.hourForEachArea(state, numSpace);
``` 
and 
```C++
for (uint j = 0; j != area.thermal.clusterCount(); ++j)
{
    state.initFromThermalClusterIndex(j, numSpace);
}
```
Will this have consequences on the output results ?

**Comment by flomnes** [comment]
Possible duplicate #1216
