### ISSUE TITLE
Add support for Oracle Linux 8

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1250]
- Add a Github Actions script
- Provide an archive/installer
- Run all tests, check that they pass
- Re-generate reference results ?

**Comment by payetvin** [comment]
Improvements:

- Prendre un OR-Tools précompilé (pas dispo encore)
- Prendre un antares-deps pré-compilé
- Prendre une image docker avec les dépendances déjà installées
- Utiliser ccache
