### ISSUE TITLE
One command to build them all

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#132]
_One command to rule them all, one command to find them, one command to bring them all, and in the darkness build them._

![One Ring](http://tolkiengateway.net/w/images/6/6a/One_Ring_inscription.png)

**Comment by sgatto** [comment]
I'm a bit lost :)
Is it because of my quest or is it the riddle?

**Comment by flomnes** [comment]
The idea would be to install all deps and compile the Antares Simulator project with one command. Because it's a bit hard for new users to compile all the deps by hand, provide the deps install dir, etc.

**Comment by jmkerloch** [comment]
This should already work for ubuntu or windows :

`cmake -B _build -S src -DCMAKE_BUILD_TYPE=release -DBUILD_ALL=ON `

But this will compile also wxWidget and all libraries that can be available on a package manager (apt-get or vcpkg).

You can use : 
`cmake -B _build -S src -DCMAKE_BUILD_TYPE=release -DBUILD_sirius=ON -DBUILD_ortools=ON`

or 
`cmake -B _build -S src -DCMAKE_BUILD_TYPE=release -DBUILD_not_system=ON`

so 'package manager' libraries are not compiled.

**Comment by sgatto** [comment]
@flomnes would you prefer these instructions to be presented differently in the install page?

**Comment by flomnes** [comment]
I will test these instructions on a fresh Ubuntu install. If they work, I think it would be nice to have them in `INSTALL.md`
