### ISSUE TITLE
Use `Simulation::ITimeSeriesNumbersWriter` for all modes (load, wind, solar, thermal, renewable, NTC)

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1322]
See **src/solver/simulation/timeseries-numbers.cpp**

Also, don't pass `time_series_writer` to function `StoreTimeSeriesNumbersIntoOuput` if possible (@JasonMarechal25 mentions dependency injection)

**Comment by flomnes** [comment]
https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1219#discussion_r1205396793

**Comment by flomnes** [comment]
The problem is that `Simulation::ITimeSeriesNumbersWriter` is not as generic as it seems.

It's `write` function looks like this
```cpp
class ITimeSeriesNumbersWriter {
public:
    virtual ~ITimeSeriesNumbersWriter() = default;
    virtual void write(const Data::BindingConstraintsList& list) = 0;
};
```
If we wanted to write other types of TS numbers, we'd need some kind of genericity on the contrary.

**Comment by pet-mit** [comment]
ANT-2170
