### ISSUE TITLE
Impossible to resize reserve matrix

### ISSUE THREAD

**Issue by benlagane** [AntaresSimulatorTeam/Antares_Simulator#1324]
**Description**
Impossible to resize reserve matrix if  we want to have a different reserves time series by Monte Carlo scenario. It would be interesting to be able to do it.

**How to Reproduce**
Just try to resize the reserves matrix

**Screenshots and additional files**
![log](https://github.com/AntaresSimulatorTeam/Antares_Simulator/assets/132365191/4f664640-02af-463b-8bdd-cc8b94885027)

**OS and version**
 - OS:  Windows, 
 - Antares Simulator version: 8.5.0

**Additional context**
This isn't really a bug (because the log that appears implies this behavior was planned in the code) but an idea of improving the software.

**Comment by flomnes** [comment]
Hi @benlagane, thank you for your feedback,
We are working to scenarize most parameters in Antares Simulator. Currently, only it's only available for wind, solar, thermal generation, link capacities. Reserves will probably be included into this.
This macro-feature will require heavy changes in the code-base. It is planned in the next 2 years, so please be patient.

A big effort is being placed also on the modelling of reserves, although I can't disclose much about this.

Finally, please acknowledge that the GUI you're using is deprecated. It is being replaced by [AntaREST/Antares Web](https://github.com/AntaresSimulatorTeam/AntaREST/), a web-based client. It is already almost iso-functional with the legacy GUI.

**Comment by benlagane** [comment]
Great I got it... But I have a question . The results present 8736 lines or 364 days. It's normal to have that in the anares 8.5.0 on Windows OS?

**Comment by flomnes** [comment]
Yes, it's normal for output files to contain 364 days. Antares simulations are based on the week (7 days), so we have results of 7*52=364 days.

You can also change some properties to add more days (simulation.start and simulation.end in file settings/generaldata.ini).

Hope that helps
