### ISSUE TITLE
ST storage : save default time series on disk

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1337]
When loading a study with at least a ST storage : 
For time series that does not exist, some default time series are built internally.

In the same spirit, when saving a study with ST storage, if a ST storage has time series with the default values,
it's all saved on disk, taking up unnecessary space.

Further more, reloading the study takes unnecessary load time.

Should we not avoid saving on disk default TS ?

**Comment by flomnes** [comment]
Not a priority, since saving a study only happens when upgrading a study. For now, no upgraded study have short-term storage.

**Comment by flomnes** [comment]
We'll stick with the logic of time-series for consistency. All of them are mandatory, even if they're full of 0 or 1.
