### ISSUE TITLE
ST storage : saving the storagecycle

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1338]
The **storage cycle** of a ST storage is currently unused.
But when saving a study with a ST storage, and then reading the related **list.ini** file, we an have : 
**storagecycle = 1937075299**
which does not have any consequence but is quite confusing

**Comment by flomnes** [comment]
This could lead to undefined behavior, cycles should be saved as well

**Comment by flomnes** [comment]
Please do not save anything related to cycles for now, since cycles will be handled differently in **v8.7.0**

**Comment by flomnes** [comment]
Won't do
