### ISSUE TITLE
ST storage : question on the storage name in list.ini 

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1340]
**Question** :
Here is an example of a ST storage **list.ini** file 
```ini
[my-sts-3]
...
name = my-sts-3
...
```
If the name between **[ ]** is the name of the ST storage, why is it repeated in **name = ...** ?

**Comment by flomnes** [comment]
It's the usual behavior. I think the section name is ignored (usual behavior)
