### ISSUE TITLE
Tests as studies for v8.6.0 : activating these tests in CI 

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1376]
Check that all tests are run in the CI
- Scenarized RHS for binding constraints - study
- Scenarized RHS for binding constraints - in-memory
- Scenarized prices for thermal generation (RTE-i's CR20) - in-memory
- Named MPS problems - study

**Comment by flomnes** [comment]
It will be necessary to re-generate results with v8.6.1 first, since STS results were wrong with v8.6.0 because of a bug fixed by #1377

**Comment by payetvin** [comment]
Looks like all tests are executed 
https://github.com/AntaresSimulatorTeam/Antares_Simulator/actions/runs/5740787800/job/15559413699
