### ISSUE TITLE
BC scenarisation : study tests for validation + non regression 

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1384]
Some new tests have to be created in order to validate the BC scenarization functionality.
These tests will be integrated in the CI automate process and will be used as non regression tests.
They will be under the form of one or more Antares studies.

**Comment by flomnes** [comment]
- Generate reference results in SimTest
- Make sure that tests are run in the CI (push/release/scheduled)
