### ISSUE TITLE
BC scenarization : what about historical GUI ?

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1386]
Currently, we don't know about the behavior of historical GUI regarding binding constraints.
Introducing multiple scenarii for BC RHS probably may have broken something.
As you know, binding constraints part of Antares is daily heavily used. 
- Will users of Antares Simulator v8.7 be able to edit, load and save binding constraints as they used to do ?
- What if a user loads an old study  (version < v8.7) with an Antares v8.7 ? And tries to update this study ?
- In case we broke something, should we change the UI code base in such a way that UI does not crash ?

**Comment by flomnes** [comment]
We should remove these panels, just leave a message "This feature is no longer available, please use Antares Web instead"
