### ISSUE TITLE
Split antarescore in several libs

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1394]
Antarescore is properly structured in directories but not in CMake subdirectories.
Having dedicated CMakeFiles for each "module" would help on several points:

- Smaller AntaresCore CMakeFile
- Prevent recompilation of all files in current AntaresCore lib when one is changed
- Simpler/More isolation of test by not depending on all antarescore but a specific subset. And allow mocking/stubbing of the rest

**Comment by flomnes** [comment]
Also make sure there are no relative includes `#include ../../src/"

**Comment by payetvin** [comment]
done in api antares
