### ISSUE TITLE
Wrong name for inflows.txt file in the readthedocs file format changes

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/Antares_Simulator#1395]
There is one mistake on the documentation https://antares-simulator.readthedocs.io/en/latest/reference-guide/13-file-format/#v860 .
The file name inflow.txt is not the name expected in the source code. It's **inflows.txt** instead with the 's'.

**Comment by flomnes** [comment]
See docs/reference-guide/13-file-format.md
