### ISSUE TITLE
Do not use indexes for active binding constraints

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1454]
Active binding constraints are returned by a function. Using fixed indexes implicitly uses the fact that this function will always return the same vector.

This assumption is not satisfied if e.g binding constraints are added after a first call to this function.

I suggest using `std::shared_ptr<BindingConstraint>` instead. Since those indexes are used to access arrays, I suggest turning those arrays into `std::map<std::shared<BindingConstraint>, double*>` or something similar.

```cpp
pValuesForTheCurrentYear[numSpace].day[dayInTheYear]
  -= state.problemeHebdo
       ->ResultatsContraintesCouplantes[bindConstraintGlobalIndex_]
       .variablesDuales[dayInTheWeek];
```

**Comment by a-zakir** [comment]
☑️
