### ISSUE TITLE
Unhandled error when writing mps in zip mode

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1469]
**Description**
No mps file generated. "Unhandled error" occurs

**How to Reproduce**
With a user study and options to export mps. Happen every time

**Expected behavior**
mps files are generated

**OS and version**
 - OS: Ubuntu 20.04
 - Antares Simulator version: 8.4.2-8.7

Etude e3ff247e-8cfd-4b00-a3cd-a02efe2ce719 sur antares

**Comment by JasonMarechal25** [comment]
Issue come from a hard limit of file size when reading a file. The error occurs only in zip mode because we write mps files in /tmp, then read them to add them to the archive. Without zip, we only write the files in output.
Hard limit is 80mo, which is small. Proposal is to increase significantly the size in a first time and open a new issue to try remove the limit in a second time

**Comment by flomnes** [comment]
Can we close this ?
