### ISSUE TITLE
[Unit tests] Remove dangerous uses of test suite fixtures

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1474]
**Description**

In most unit test, we share fixtures between all the test cases of a test suite, through the use of the macro 
```cpp
BOOST_FIXTURE_TEST_SUITE(s, Fixture)
```
This is dangerous, because test cases will share and modify the same data, typically a study.
Instead, each test case should have its data isolated from other test cases.

**Fix**

We should favor the use of `BOOST_FIXTURE_TEST_CASE` instead.

**Comment by a-zakir** [comment]
Push the button (lost)
