### ISSUE TITLE
Use reference instead of Study::Ptr in functions of tests

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1476]
Not directly related to that PR but:

Instead of using a shared_ptr, the best thing would be to clarify if this handler should have ownership of the study (I don't think so).
If not, we can just pass a reference here.
shared_ptr should be used only when shared ownership is actually required.
Then we wouldn't need the move :)

_Originally posted by @sylvlecl in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1388#discussion_r1276302773_

**Comment by pet-mit** [comment]
ANT-2162
