### ISSUE TITLE
Improve shared_ptr/reference/raw usage in tests functions

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1477]
This helper class is clearly not an owner of the BC: we should provide it a reference instead of shared_ptr.
(possibly for later work since it has not been done in this PR)

_Originally posted by @sylvlecl in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1388#discussion_r1278929930_

**Comment by pet-mit** [comment]
ANT-2161
