### ISSUE TITLE
Compare hourly min gen & max gen for hydraulic

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1478]
Since v8.6.0

It is currently possible for the user to provide trivially invalid data. The solver crashes because of an infeasible problem.

We should check that mingen[h] <= maxgen[h] for every h.

**Comment by flomnes** [comment]
It's impossible to check this in advance, since `WeeklyGeneratingModulation` is not known in advance, but computed for every week based on the final reservoir from the previous week.

It uses a linear interpolation using "creditModulation". See src/solver/simulation/sim_calcul_economique.cpp, calls to function `getWeeklyModulation`.

A possible way is to take the worst case, but it seems too restrictive.

**Comment by flomnes** [comment]
Another way is to also apply this modulation to the minimum hourly generation.

Currently, we have
```
mingen[h] <= prod[h] <= mod[h] * maxP[h]
```
where mod[h] is computed based on the previous reservoir level. We could instead apply
```
mod[h] * mingen[h] <= prod[h] <= mod[h] * maxP[h]
```

So that we can check `mingen[h] <= maxP[h]` before the simulation (this is possible).

**Comment by Milos-RTEi** [comment]
Just came to my mind that the check: Hourly minimum generation <= hourly max for each hour
is performed only if: area.hydro.reservoirManagement = false
according to the code we developed:
[the comment in the function is also wrong mingen[h] is not compared to inflows (like in weekly, monthly, and yearly checks) it is compared to maxgen[day]] - copy paste errors
![image](https://github.com/AntaresSimulatorTeam/Antares_Simulator/assets/97689304/48552350-d064-4bad-a27c-4092dbd72a59)

But according to the specification we agreed on it should be checked for all scenarios:
![image](https://github.com/AntaresSimulatorTeam/Antares_Simulator/assets/97689304/c668e258-36f3-4273-b581-f00176c572b6)

spec: https://rteinternational.sharepoint.com/:w:/r/sites/AntaresUser%27sClub-Interne/Documents%20partages/Change%20Requests/Selected%20for%20development/CR22%20-%20Multiple%20Minimum%20Generation%20for%20Hydro%20Reservoirs/Functional_Specifications-Multiple_min_gen_for_hydro_clusters_V0.1-HA.docx?d=web3abdf476d94fc8adca58d741bffb94&csf=1&web=1&e=wfbOie

so the "if (!area.hydro.reservoirManagement)" is redundant here. 

This is btw corrected when implementing hourly max generation and pumping for hydro. https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1470

**Comment by payetvin** [comment]
done
