### ISSUE TITLE
Thermal cluster lists : simplify and clarify

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1487]
There are many cluster lists for an area : 
- **src/libs/antares/study/parts/thermal/container.h** : `ThermalClusterList list->mapping;` 
- **src/libs/antares/study/parts/thermal/container.h** :  `ThermalClusterList mustrunList;`
- **src/libs/antares/study/parts/thermal/container.h** ; `std::vector<ThermalCluster*> clusters;`
- **src/libs/antares/study/parts/common/cluster_list.h** : `Map cluster;`
- other lists ?

It's confusing, and it's pretty sure that the number of cluster lists can be reduced.
We should have a deep look into this in order to simplify and clarify

**Comment by flomnes** [comment]
Note that the logic is similar for renewable clusters, as well as short-term storages. This PR also applies to those.

**Comment by flomnes** [comment]
@guilpier-code

## Proposal
Remove `std::map`, keep the `std::vector`s and `std::sort` them in the loading function, after the loading has been completed.

- For thermal clusters, only keep `std::vector<ThermalCluster> clusters`, remove `ThermalClusterList list` and `ThermalClusterList mustrunList`.
- For short-term storage, only keep `std::vector<STStorageCluster> storagesByIndex`, remove `std::map<std::string, STStorageCluster> storagesById`.
- For renewable clusters, only keep `std::vector<RenewableCluster> clusters`, remove `RenewableClusterList list`.

**Comment by payetvin** [comment]
For renewable clusters, keep `RenewableClusterList list`,  removed `std::vector<RenewableCluster> clusters`
