### ISSUE TITLE
Documentation about TS generation

### ISSUE THREAD

**Issue by Schlegen** [AntaresSimulatorTeam/Antares_Simulator#15]
Hello,

Thanks for your impressive work.

I am interested by your method of generation of time series. So, what method do you use ? Do you have some documentation about it ?

Thank you in advance for your reply

**Comment by flomnes** [comment]
This feature is mostly undocumented. Efforts should be made to add documentation.

**Comment by flomnes** [comment]
https://antares-simulator.readthedocs.io/en/stable/reference-guide/06-time_series_analysis_and_generation/
