### ISSUE TITLE
Iterators over values instead of (smart) pointers

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1512]
**Description**

#1388 introduced new repositories which manage the lifetime of underlying objects through smart pointers.
This should remain an implementation detail of those classes.
Therefore, the getters and iterators of those classes should not expose smart pointers, or iterators over smart pointers, but references and iterators over values instead.

In order to implement iterators over values instead, we can use `boost::indirect_iterator`.

**Note**

There is likely other existing places in the code where a similar change would be relevant.

**Comment by pet-mit** [comment]
ANT-2159
