### ISSUE TITLE
Final reservoir levels : use of constructor instead use of setter methods

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1534]
In class **FinalLevelInflowsModifier**, we have : 
- a **constructor**
- a **initialize(...)** method, which is a setter

For code sanity, we would like to move the setting of some data members from  **initialize(...)** to the **constructor**.
The data setting to be moved is **scenario builder matrices** on **initial and final levels**.

In order to do that , we need this data to be available when constructing the hydro part of an area, but it's currently not available, and for 2 reasons : 
- this data on scenario builder is not loaded yet,
- even it was loaded, it would be available when constructing an area, therefore indirectly  (see **src/libs/antares/study/area/list.cpp** : AreaListAddFromNames(...)), via the **pStudy** of class **AreaList**.

So how to do that ?

**Comment by payetvin** [comment]
done in CR25
