### ISSUE TITLE
Simplification of Variables design

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1541]
**Description**

The variables module has a very complex design, including chained lists of templates.

The contract for variables is not explicit, making it error prone.

Instead, we should use a more classic design where:
- variables all implement the same interface
- list of variables are plain classes, not chained templates

**Implementation note**
I am aware that this brings some computation from compilation time to runtime, but it will clearly make NO difference overall in a computation ...

**Comment by flomnes** [comment]
We may find surprising details in the current implementation, though.

**Comment by flomnes** [comment]
We may find surprising details in the current implementation, though.

**Comment by pet-mit** [comment]
ANT-2119
