### ISSUE TITLE
Remove dynamic allocation for "probleme a resoudre"

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1555]
**Description**

It seems that we could void dynamic allocation of `ProblemeAResoudre` in `PROBLEME_HEBDO`.
However, some logic seems related to the absence of that field, which might remain necessary:
we need to investigate a little to confirm this or not.

**Origin**
Will leave it aside for now.
There is logic revolving around ProblemeAResoudre being null that can't be translated using a value

_Originally posted by @JasonMarechal25 in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1549#discussion_r1295879410_

**Comment by flomnes** [comment]
See Remove dynamic alloc of PROBLEME_HEBDO (#1554)
