### ISSUE TITLE
Reduce test executables size

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1563]
**Description**
End-to-end test executables are really large, around 50M.
As we start to have a few, we should worry about the total size of the build output.

Possible solutions will be:
- link with antares libraries as shared libraries
- create fewer executables by gathering tests in common executables (still different test suites)

**Comment by flomnes** [comment]
A "quick win" is to create one large .so, link all test executables against it. Not sure it's possible or easy, though.

**Comment by payetvin** [comment]
strip symbols

**Comment by pet-mit** [comment]
ANT-2158
