### ISSUE TITLE
Remove variable numSpace

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1571]
Basically, we have structures whose member data is duplicated for multi-threading, and indexed by numSpace, the thread number.

My advice would be to confine this `numSpace` variable to the highest level, so that this implementation detail doesn't leak everywhere. I think this work will mainly concern the code that generates the output, which is where most occurrences of `numSpace` are found. There are also a few in the hydro heuristics code.

Example (**src/solver/variable/economy/inflow.h**)
```cpp
void initializeFromStudy(Data::Study& study)
{
    pNbYearsParallel = study.maxNbYearsInParallel;

    InitializeResultsFromStudy(AncestorType::pResults, study);

    pValuesForTheCurrentYear = new VCardType::IntermediateValuesBaseType[pNbYearsParallel];
    for (unsigned int numSpace = 0; numSpace < pNbYearsParallel; numSpace++)
        pValuesForTheCurrentYear[numSpace].initializeFromStudy(study);

    // Next
    NextType::initializeFromStudy(study);
}
```

**Comment by payetvin** [comment]
`numspace` is named `thread_number` in code related to adequacy patch (mainly in `src/solver/optimisation`)

It should be renamed `numspace` for consistency

**Comment by flomnes** [comment]
As of June 2024, there are 2211 matches for `numSpace`, out of which 2123 matches in **src/solver/variables**. It seems tricky to remove it.

**Comment by pet-mit** [comment]
ANT-2117
