### ISSUE TITLE
Break down exceptions and dispatch to respective modules

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1587]
"Exception" group all the exceptions of the programme. The issue is that it currently depends on AreaName meaning that anything (i.e. benchmarking) that depends on it also depends on AreaName (fwd.h to be precise).

Exceptions should be defined by the libs that throw them so that only clients of said libs need to depends on those exceptions.

**Comment by pet-mit** [comment]
ANT-2156
