### ISSUE TITLE
Library name conflict when building deps (ortool)

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1589]
**Description**
A CMake error occur when building simulator and its deps when two libraries happen to have the same name.
This occurs because everything is build in the same place

**How to Reproduce**
Have a library in antares with the same name as a third party like in ortools. e.g. memory

**Expected behavior**
It should be possible to name a library in Antares with any name

**Screenshots and additional files**
https://github.com/AntaresSimulatorTeam/Antares_Simulator/actions/runs/5965108665/job/16181788319
`-- {antares}  Antares Core library
CMake Error at libs/antares/memory/CMakeLists.txt:12 (add_library):
  add_library cannot create target "memory" because another target with the
  same name already exists.  The existing target is an interface library
  created in source directory
  "/__w/Antares_Simulator/Antares_Simulator/_build/_deps/absl-src/absl/memory".
  See documentation for policy CMP0002 for more details.

CMake Error at libs/antares/memory/CMakeLists.txt:15 (target_link_libraries):
  INTERFACE library can only be used with the INTERFACE keyword of
  target_link_libraries

CMake Error at libs/antares/memory/CMakeLists.txt:23 (target_include_directories):
  target_include_directories may only set INTERFACE properties on INTERFACE
  targets

-- {antares}  Antares Filesystem Walker library
-- {antares}  Antares Solver
-- {antares}    :: application solver
-- {antares}  antares-analyzer`

**OS and version**
 - OS: Oracle8
 - Antares Simulator version: 8.7

**Additional context**

**Comment by sylvlecl** [comment]
**To be discussed**
I would be in favor of not including dependencies in the project build with the "fetch content" cmake feature.
Instead, I think using **only imported targets** would isolate more the build of our own code, and also avoid to go over dependencies that are almost never modified during each build.
Imported targets will never conflict with our targets thanks to namespaces.

This means that all dependencies would be built in a separate cmake tree (like antares-deps already is today, actually).

Note that we could offer a "super build" which would incorporate both the dependencies build and the project build as 2 "external projects" (seen this setup on stackoverflow). But not sure it has a large added value compared to the manual 2-steps build.

**Comment by flomnes** [comment]
@JasonMarechal25  @sylvlecl  Can we close this ticket or is it still relevant ?

**Comment by payetvin** [comment]
done
