### ISSUE TITLE
`antares-8.5-solver` fails because of xpress even though i did not want to use this solver

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/Antares_Simulator#1591]
**Description**

I wanted to launch a v8.5 study with `antares-8.5-solver` without using xpress. 
But the solver found the version 9.0 of xpress on my computer and the simulation failed with this log : 

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0825 14:30:59.790609 88622 environment.cc:2273] Found the Xpress library in /home/belthlemar/installation/xpress/lib/libxprs.so.
F0825 14:30:59.790642 88622 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function XPRSloadqglobal in /home/belthlemar/installation/xpress/lib/libxprs.so
*** Check failure stack trace: ***
```

**How to Reproduce**

Launch a v8.5 study with  `antares-8.5-solver`  whithout specifying that you want to launch it with xpress.
You also need on your computer an xpress version at least as recent as the v.9.0

See that the simulation fails.

**Expected behavior**

I expect `antares-solver` to ignore the xpress distributions on my computer if i do not specify that i want to use it.
In this case, i also expect the solver to suceed by using sirius.

**Additional context**

Florian Omnes said to me that `antares-8.5-solver` is not compatible with such recent xpress distribution and that's why it failed.
It could be nice to have somewhere in the documentation a cross table of compatible versions between antares and xpress.

**Comment by flomnes** [comment]
This is a known bug. Please use XPRESS 8.13.0 as indicated [here](https://antares-simulator.readthedocs.io/en/latest/reference-guide/16-xpress/).
