### ISSUE TITLE
No tests run with OR-Tools (Sirius, Clp, XPRESS, etc.)

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1592]

**Comment by flomnes** [comment]
The Community licence for XPRESS is quite restrictive, allowing only very small optimization problems. For example, we can execute study **001 One node - passive** (1 thermal cluster, uc-mode=fast), but not **008 Thermal fleet - Accurate unit commitment** (3 thermal clusters, uc-mode=accurate).

**Comment by pet-mit** [comment]
ANT-2132
