### ISSUE TITLE
A few liblib* CMake targets

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1602]
Example
```
[ 89%] Linking CXX static library liblibantares-solver-main-adequacy.a
[ 89%] Linking CXX static library liblibantares-solver-constraints-builder.a
```

CMake automatically adds the "lib" prefix.

We can either
- Leave it as it is now
- Remove this prefix from CMake [CMAKE_STATIC_LIBRARY_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_STATIC_LIBRARY_PREFIX.html)
- Remove it from our CMakeLists.txt

**Comment by JasonMarechal25** [comment]
IMO third options "Remove it from our CMakeLists.txt".
We see from logs that the repetition shouldn't occur. By convention CMake targets name don't use libX just X
