### ISSUE TITLE
Remove NaNs from results

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1603]
These pose problems to Antares Web, possibly scripts.

**Comment by payetvin** [comment]
@MartinBelthle still a problem ?

**Comment by MartinBelthle** [comment]
Not really. It was at the time this issue was created but we did a development to fix the issue on our side so now it's not an issue anymore.

**Comment by pet-mit** [comment]
ANT-2154
