### ISSUE TITLE
Discrepancy between the aggregate results calculated by AntaresSimulator and the values recalculated from hourly outputs

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1608]
In various studies, we note a discrepancy between the aggregate results calculated by AntaresSimulator and the values recalculated from hourly outputs.
 
Example: Study **3cb89be9-b5f6-48bb-a326-5d699e807a83**, only one week simulated, the third (July 10 to 16).

Weekly outputs for the AT zone

> The sum of hourly system costs over the week is 6857988
> The weekly value of system costs returned by Antares is 6857994

Daily output for AT zone

> The sum of hourly system cost values over the week is 1907244
> The weekly value of system costs returned by Antares is 1907247

This is probably due to an index shift in the calculations.

Need to check also the monthly output, likely affected by the same bug.

**Comment by flomnes** [comment]
### Rounding errors

Changing file **src/solver/variable/economy/overallCost.h** yields a difference of 10^-6 in the aggregated OV. COST weekly value (from 6)

```diff
-        decimal = 0,
+        decimal = 10,
```

**Comment by sylvlecl** [comment]
Closing since the difference is due to rounding in outputs, see above.
