### ISSUE TITLE
Move antares-deps and Antares_Simulator_Tests outside of src

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#165]
Having these two folders inside src slows down code search a lot.

**Comment by a-zakir** [comment]
Brilliant

**Comment by flomnes** [comment]
It is possible to exclude folders / patterns in most search tools.

**Comment by payetvin** [comment]
antares-deps removed, needs to be done for Antares_Simulator_Tests

**Comment by pet-mit** [comment]
ANT-2181
