### ISSUE TITLE
Spinning value 100 should not be accepted, it causes silent errors

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1662]
It produces `nan` values in generated time-series for thermal clusters

```
-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan
-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan	-nan
```

**Comment by flomnes** [comment]
Just before writing thermal TS to the input directory, the `ThermalCluster::reverseCalculationOfSpinning` function is called on all thermal clusters.

If `spinning=100`, it divides the values by 0, leading to `NaN`.

It should be noted that these NaN values are **not** used for the computation since `importTimeseriesIntoInput` is called after the simulation.

**Comment by pet-mit** [comment]
ANT-2152
