### ISSUE TITLE
Build for Ubuntu 23.04 and Debian 12

### ISSUE THREAD

**Issue by maurerle** [AntaresSimulatorTeam/Antares_Simulator#1690]
With Debian 12 and Ubuntu 23.04 - the dependency `libwxgtk3.0-gtk3-0v5` does not exist anymore.
It is replaced by `libwxgtk3.2-dev`

Would it be possible to provide a release for this too?
I somehow had problems building it myself changing the `src/CMakeLists.txt` 

```
-- DEPS_INSTALL_DIR : /home/admin/fh-gitlab/projects/Antares_Simulator/src/../../rte-antares-deps-release
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  CMakeLists.txt:230 (find_package)
```

**Comment by maurerle** [comment]
On debian12 i had to run:

```
git submodule update --init src/antares-deps
sudo apt-get install git unzip cmake build-essentials uuid-dev libboost-test-dev libwxgtk3.2-dev python3-numpy python3-pytest
cmake -B _build -S src -DCMAKE_BUILD_TYPE=release
cmake --build _build --config release -j8
```

then I ran `./_build/ui/simulator/antares-8.7-ui-simulator` and used antares.
So other than the updated dependency, it works on Debian12 too.
I do not know what is the best way to ensure that either of the two dependencies is installed (`libwxgtk3.2-dev` or `libwxgtk3.0-gtk3-0v5`) 


Edit: i know now - one can use the pipe operator (`|`) for that

**Comment by flomnes** [comment]
Hi @maurerle, the GUI is deprecated in favor of [Antares Web](https://github.com/AntaresSimulatorTeam/AntaREST).

It is no longer maintained internally.

However, you may submit a PR with instructions on how to build Antares GUI on debian 12.

**Comment by maurerle** [comment]
Hi @flomnes - wouldn't it be good to mention antares web then in the README of Antares_Simulator?

Thanks I just did :)
