### ISSUE TITLE
Crash when NTC time series have negative values

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1698]
**How to reproduce** : 
If you create a study with the **GUI** and you want to set some NTC with negative values, you can't : GUI prevents you from doing that.
But you can do this by hand : go to input directory, and find a **\<some area\>_direct.txt** or **\<some area\>_indirect.txt**, then replace some values with -10 (for instance).

Once done, run the study.

**The crash** :  
The NTC negative values are detected and an error message is logged, no problem with that.
But the solver crashes after quitting gracefully (see logs : **[UI] Quitting the solver gracefully**).

**Note** : 
Strangely, we have the log line :  **[UI] Quitting the solver gracefully** (notice the **[UI]**) even if we only run the solver.
We should take care of this as well.
 
**Observed on** :
- **Windows**.
- **Antares** v8.7.0

**Comment by flomnes** [comment]
See #1685 for possible fix.

> The NTC negative values are detected and an error message is logged, no problem with that.

@guilpier-code Can you copy-paste the error message ?
