### ISSUE TITLE
Trailing remarks on issue 1699

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1700]
We should take care of some untreated remarks in #1699 
This work seems simple and should take long.

Remarks : 
- [this one](https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1699#discussion_r1356367254)
- [this one](https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1699#discussion_r1356379355)

**Comment by payetvin** [comment]
will be removed with GUI
