### ISSUE TITLE
All tests are not run in CI

### ISSUE THREAD

**Issue by payetvin** [AntaresSimulatorTeam/Antares_Simulator#1731]
For example [valid hydro](https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests_NR/tree/main/valid-hydro) isn't run in Ubuntu and Windows CI.

We should have a way to run all NR tests in a simpler way, currently we need 5 lines for each test type.

**Comment by a-zakir** [comment]
I could not agree more with @payetvin

**Comment by a-zakir** [comment]
One line would be 👌🏽

**Comment by pet-mit** [comment]
ANT-2130
