### ISSUE TITLE
Mocking library for unit tests

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1733]
**Description**

Some unit tests would benefit from using a mocking library, instead of hand-written mocks.

In particular, the UT introduced in pull request https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1716 would be written more easily with that.

**Solution**

A natural candidate for this is google mock. Its usage will require to update the CI and documentation with that new dependency.

**Comment by pet-mit** [comment]
ANT-2149
