### ISSUE TITLE
Ensure we cover multi-threaded use in regression tests

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1737]
**Context**
When working on removal of `space` concept, we broke the thread safety in hydro management class, but this did not break any regression tests.
Therefore, it seems that multi-threaded behaviour is not well enough covered by regression tests.

**Goal**
Ensure non regression on multi-threaded behaviour, by having regression tests with parallelism enabled for all features that might use it.

**Comment by a-zakir** [comment]
Intéressé

**Comment by payetvin** [comment]
done in parallel tests
