### ISSUE TITLE
antares-solver should fail when OR-Tools solver is not found

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1739]
**Description**

In version 8.8, when you use options `--use-ortools` and `--ortools-solver=***`, and when the corresponding solver is not found or invalid, antares silently backs up to using sirius (with a small warning log actually).

This is dangerous, because one can easily not see that we did not use the requested solver.

Instead, we should exit on an error message.

**Comment by a-zakir** [comment]
_Then_ why are we calling sirius directly if —use-or tools is not used??_

**Comment by a-zakir** [comment]
sorry misunderstood
