### ISSUE TITLE
[Build] Remove DEPS_INSTALL_DIR in favor of standard CMAKE_PREFIX_PATH

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1742]
**Description**

Currently, configuring the project requires to define a special variable `DEPS_INSTALL_DIR` to define where antares-deps was installed.

This is not needed and not standard, we should rely instead on the standard CMAKE_PREFIX_PATH to define where those dependencies are installed.
There is some xpansion-related code that needs to be checked, though:

https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/a630959fccd1fddf5e52de622876de4cd54560ac/src/CMakeLists.txt#L201C1-L218

@JasonMarechal25 do you know the background of this `DEPS_INSTALL_DIR_XPANSION` variable ?

**Comment by a-zakir** [comment]
`CMAKE_INSTALL_PREFIX`

**Comment by pet-mit** [comment]
ANT-2129
