### ISSUE TITLE
Cmake helper functions for tests

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/Antares_Simulator#1748]
**Description**

Adding unit tests involves a few instructions which need to be repeated for each test.
They are sometimes forgotten, leading to  mistakes, see for example #1744 .
```cmake
add_executable(<executable>)
... 
# For VS folder
set_target_properties(<executable> PROPERTIES FOLDER Unit-tests/<folder>)
add_test(NAME <test> COMMND <executable>)
set_property(TEST <test> PROPERTY LABELS unit)
```

We should provide one or more helper functions to avoid the need for those repeated instructions, for example
`antares_add_unit_test`, `antares_add_e2e_test` ...

**Comment by pet-mit** [comment]
ANT-2128
