### ISSUE TITLE
Simulation -> "Store in input" option not working

### ISSUE THREAD

**Issue by Milos-RTEi** [AntaresSimulatorTeam/Antares_Simulator#1760]
**Description**
Time Series, generated using Stochastic TS generator, are NOT properly stored in input (output is always only 1 column off all zeros). 
Note: Time Series, generated using Stochastic TS generator, are properly stored in output.

**How to Reproduce**
Try to generate any Time Series (load, thermal, hydro..).
Inside the "Simulation" Window, set options for "Stochastic TS": 
Status-ON, 
Number - any number, 
Store in input = Yes, 
Store in output = Yes, 
other inputs in simulation window are not important. 
Note: Inside e.g. Thermal->Cluster_Name->"TS Generator" Window - values, different from default ones, need to be added, to avoid generating 1TS of all zeros.  

**Expected behavior**
Generated TS should be visible at Thermal->Cluster_Name->Availability[MW] when "Store in input" option is set to Yes.

**Screenshots and additional files**
-

**OS and version**
 - OS: [Linux - Ubuntu 20.04]
 - Antares Simulator version: [8.7.0]

**Additional context**
-

**Comment by payetvin** [comment]
GUI depreciated
