### ISSUE TITLE
set "vendor" in the windows installer

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/Antares_Simulator#178]
When running the Antares installer on Windows, a pop-up shows up : "Windows a protégé votre ordinateur" (french)
Clicking on "Informations complémentaires" (french), we read "Editeur inconnu" (publisher is unknown).

Prevent Win OS to trigger this warning.

**Comment by guilpier-code** [comment]
It seems that the only way to remove this pop-up when running installer is to get a software publisher certificate (**SPC**)  from a certificate authority (**CA**) allowed by Windows. This certificate is charged.
More precisely : 
- we have to get the certificate (**SPC**) from a **CA**
- the certificate authority (**CA**) will provide a private and public key for the certificate (**SPC**)
- if needed, the certificate (**SPC**) must be converted into a Personal Information Exchange (.pfx) file.
- we also need an associated cross certificate. Cross-certificates provide a means to create a chain of trust from a single, trusted, root CA to multiple other CAs.
- we need to make NSIS take into account the **SPC**. For this, better to have NSIS v3 and use command **!finalize**.

General information about **SPC** (and cross-certificates) : 
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/obtaining-a-software-publisher-certificate--spc-

For a list of cross-certificates along with the associated **CAs** : 
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing

For use of NSIS v3's **!finalize** command : 
https://stackoverflow.com/questions/10581570/setting-the-uac-publisher-field-for-a-nsis-installer
