### ISSUE TITLE
Remove uses of Yuni::String, Yuni::AnyString, Yuni::Clob, etc.

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1781]
Use `std::string`, `std::istringstream`, etc.

**Comment by sylvlecl** [comment]
For reference:
the removal of `Yuni::String` has been started in #1546, with implicit conversions between yuni and std string to ease the migration.

**Comment by a-zakir** [comment]
Could you be exhaustive ?
File by file
