### ISSUE TITLE
Add tests in example tests repo

### ISSUE THREAD

**Issue by payetvin** [AntaresSimulatorTeam/Antares_Simulator#1803]
We should keep [this repo](https://github.com/AntaresSimulatorTeam/Antares_Simulator_Examples) updated with our studies concerning new/updated features like short term storage, binding constraints...

**Comment by a-zakir** [comment]
so think you can dance?

**Comment by payetvin** [comment]
@JMJ-rte We should discuss on this topic, maybe more functionnal

**Comment by pet-mit** [comment]
ANT-2148
