### ISSUE TITLE
charts for tests comparison

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/Antares_Simulator#1805]
As discussed with the team, it would be great to draw charts as tests comparison between:

- two branches
-  Simtest releases

in a gh page?

**Comment by flomnes** [comment]
@a-zakir Can you try and setup [Continuous Benchmark](https://github.com/marketplace/actions/continuous-benchmark) on this repo ? We tried a few months ago, but failed

**Comment by a-zakir** [comment]
> @a-zakir Can you try and setup [Continuous Benchmark](https://github.com/marketplace/actions/continuous-benchmark) on this repo ? We tried a few months ago, but failed

I will try

**Comment by payetvin** [comment]
#1875
