### ISSUE TITLE
Short term storage saving

### ISSUE THREAD

**Issue by payetvin** [AntaresSimulatorTeam/Antares_Simulator#1808]
` ShortTermStorage::Properties::saveToFolder` erase the list.ini file due to truncate option when opening the file.

- [ ] Find a way to save multiple clusters
- [ ] Handle few remaining remarks of #1804

**Comment by a-zakir** [comment]
so "app" will fit

**Comment by payetvin** [comment]
fixed in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1807
