### ISSUE TITLE
Replace Yuni::GetOpt::parser with something else

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1819]
GetOpt::parser is a Yuni component that parser the command line options.

In an effort to remove Yuni and tend to use industrial standards it would be best to replace it with more commonly used solutions.

Some potential (but not limited to) candidates are:

- Boost::program_options
- https://github.com/jarro2783/cxxopts
- https://cliutils.github.io/CLI11/book/
- https://github.com/p-ranav/argparse

Some key points to consider to choose one over the other:

- Acceptation: is it used and widely used by the community or in the industry
- Maintenance: Is it actively maintained and can we expect maintenance in the future
- Integration: how difficult is it to integrate in the application
- Complexity: how difficult is it to use
- Content: which features are provided

One interesting feature would be to be able to describe the options in a configuration file for better comprehension, readability and documentation.

**Comment by payetvin** [comment]
Boost: + already used in Antares - i find the syntax more complex than the other choices
cxxopts: + lightweight, only a hpp file to include
cli11: + only a hpp file
argparse: easy to download with cmake as a dependency

**Comment by flomnes** [comment]
Another factor to consider is the ability to read parameters from a configuration file. Grouping CLI parameters & a config file in the same place would be much better than the current "manual" approach.

**Comment by pet-mit** [comment]
ANT-2147
