### ISSUE TITLE
Improve data entry point for simulator as a lib

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1821]
Currently the only entrey point possible to use simulator as a library is Application::prepare(int, char*[])

This signature suppose to pass parameters as if taken from a CLI, with argv[0] being a name for the program and so on.

Another issue is that simulator fills two data structures from CLI options and mutate the values of those structures afterwards.

The goal is to provide a single structure (or meta structure) to the entry point. This structure can be filled by a client or by simulator main after CLI parsing. The structure is unmutable and the current mutation will take place in a second, dedicated structure.

![API_Input_proposal](https://github.com/AntaresSimulatorTeam/Antares_Simulator/assets/45510813/b1fbc465-20ba-459e-9e30-503ee3439527)

**Comment by a-zakir** [comment]
C heritage: argv[0] is the application itself!

otherwise i don't get why are we talking about CLI if the goal is using Antares as lib????
why Antares does not simply expose functions, classes etc...

**Comment by payetvin** [comment]
Interaction with Andromede, could be a problem

**Comment by pet-mit** [comment]
ANT-2146
