### ISSUE TITLE
Improve simulator lib API

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#1822]
Currently simulator is not designed to be used as a library. It is "simple" to expose Application and to call prepare and execute to run the simulation then get the result back.

However it would be best to design a proper, even if minimalist, API.

It should be possible to construct and execute a simulation without error. Currently if prepare has not been called I don't know if it does nothing, or fail. Having to call prepare is a exemple of temporal coupling that need to be solved.

The API should at minimum expose an object (let's call it Antares to avoid confusion with existing Solver or Simulation) with the following API (name can be changed)

- Antares(InputData)
- Antares::execute() -> results and status

**Comment by a-zakir** [comment]
will you do that?
