### ISSUE TITLE
Legacy GUI & binding constraint of type "both"

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#1826]
**Description of the bug** :  
When creating BC of type"both" with legacy GUI, saving this change causes a **misleading** error message : 
**"Cannot load time series of type other that eq/gt/lt"**.
Note that it does not occur with any other binding constraint type : **greater**, **less**, **equal**.

**Context** :
Remind that, since **GUI** v8.7, whatever the type of **BC** (binding constraint) we want to create, we cannot we create a whole **BC** with the GUI : we can create the **BC**, but, within the **BC**, giving coefficients to link flows or thermal productions is **impossible**, as well as setting **RHS** values.

**How to reproduce** : 
- Create an empty study with one area.
- Add a **BC** of type **both**
- Without trying to give values to **LHS** assets or to **RHS**, save the study
- The error message pops up

**Version** : 
- GUI v8.7
- System : at least on Win

**Comment by payetvin** [comment]
GUI deprecated
