### ISSUE TITLE
refresh span set to zero leads to a crash

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/Antares_Simulator#186]
The crash occurs on any study with time series to be generated (see : **GUI > Simulation > Time-Series Management**) : 
- when turning **refresh** to **Yes**,
- when turning **refresh span** to **0**,
- And trying to save the study.

The last action causes the crash, but we have no crash if **refresh span** is not **0**.

- [ ] the GUI should not allow for values smaller than 1
- [ ] reading 0 from the ini file should not lead to a crash (reading span=0 should deactivate the refresh)

**Comment by guilpier-code** [comment]
Which crash ? on which study ?

**Comment by guilpier-code** [comment]
For your information, the 2nd point of the current issue (what if refresh span is 0 on disk) is already taken care of. No need to treat it.
