### ISSUE TITLE
error on hydro study with playlist use and stochastic TS refresh span

### ISSUE THREAD

**Issue by jmkerloch** [AntaresSimulatorTeam/Antares_Simulator#190]
There is an error when launching a hydro study with playlist use and refresh span (see study [069 Hydro Reservoir Model -enhanced-02-custom.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/6070000/069.Hydro.Reservoir.Model.-enhanced-02-custom.zip)) : 

![image](https://user-images.githubusercontent.com/53606373/109676862-658e0e80-7b79-11eb-93c6-094215cadce9.png)

This is seems to be cause by the use of playlist with stochastic TS refresh span : 

![image](https://user-images.githubusercontent.com/53606373/109677132-a8e87d00-7b79-11eb-8a75-3cca80312bd4.png)

![image](https://user-images.githubusercontent.com/53606373/109677174-b30a7b80-7b79-11eb-8a46-be74db62dfbd.png)

If refresh span is disabled or first MC year is activated there is no issue with the study.

**Comment by guilpier-code** [comment]
Here is another example of study that crashes for "hydro and playlist reasons" : 
[H700-00.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/6069786/H700-00.zip)

The study characteristics are : 
- 1 area
- 10 MC years
- Hydro hot start is yes (on this study, if hydro hot start is no, the study does not crash)
- reservoir management is yes (so the study manages hydro levels)
-  playlist is active and has 1 year active (year n°3). The 9 other ones are disabled.
-  Hydro refresh is yes and hydro refresh span is every 2 years.

Reason of crash : the hydro start level of year 3 is negative (-1)
