### ISSUE TITLE
Use OR-Tools 9.8-rte1.0 on branches 8.6.x and 8.7.x

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1905]
# Why ?
OR-Tools 9.8-rte1.0 fixes performance issues with XPRESS. Some users would like to use this on branches 8.6.x and 8.7.x.

# Cherry-pick
1. Cherry-pick some commits (d8b2407aa, bdead1b51, probably also 670628e3a because of some issues with `CMAKE_BUILD_TYPE`) 
2. Fix conflicts
3. Create releases

# new_release.yml
Allow releases on other branches than `develop`

**Comment by payetvin** [comment]
https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1916

**Comment by payetvin** [comment]
Done 
https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/tag/v8.6.5
https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/tag/v8.7.3
