### ISSUE TITLE
Grey out monte carlo builder if building mode is set to automatic

### ISSUE THREAD

**Issue by jorritvm** [AntaresSimulatorTeam/Antares_Simulator#2]
Tdoay, a user can still configure the monte carlo builder, even if the building mode is set to automatic.
This might lead the user to believe that he is changing the way the timeseries are combined even though he isn't.

Also, if you are using flowbased  the results will be off because the right hand side is in a thermal time series list.

Therefor I think it would be best to grey out the monte carlo scenario builder option when the setting is set to auto.

This would be in line with for example results filtering, where you can only see the filtering options in the inspector when the setting is set to custom.

**Comment by guilpier-code** [comment]
Hello joritvm,
thanks for pointing this issue.  
a fix will be available is the next version (it should be version 8.0) coming very soon.
Sorry for taking so long to take care of this issue.
In the future, we 'll try harder to (at least) answer earlier.
