### ISSUE TITLE
Extra field storagecycle on v8.6.6

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#2037]
> qu'on travaille dessus avec Antares Simulator et qu'on utilise le fonction Save (ou Save as), l'étude vient écrire un champ supplémentaire dans les fichiers list.ini des clusters de stockage CT, ce qui les rend ensuite illisibles par AntaresWeb (Erreur indiquant "extra fields not permitted"). Le champ supplémentaire écrit est "storagecycle = 143".

**Comment by payetvin** [comment]
#2195
