### ISSUE TITLE
Wrong weighting for the PSP/MISC. NDG synthetic mean calculation

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#206]
**Description**
The weighting of the PSP and MISC. NDG variables seem incorrect in the synthetic mean results. 

**How to Reproduce**
The study below was run on 3 MC years, with the following weighting factors: 1, 2, 3.
For these 3 years, for the area "BG", on the first timestamp, the values of the variables PSP and MISC. NDG are the following :
- PSP = 711 MW
- MISC. NDG = 129 MW

However, the mean value for these variables in the synthetic results are PSP = 356 MW and MISC. NDG = 65 MW. 

This problem is also noticed with different weightings specified.

**Expected behavior**
As the value of these variables is identical for the three simulated years, the weighted mean should have the same value as well.

**Screenshots and additional files**
[TP2_Viz_2_V8_simplified.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/6191049/TP2_Viz_2_V8_simplified.zip)

**OS and version**
 - OS: Windows
 - Antares Simulator version: V8.0.0

**Comment by jmkerloch** [comment]
There is an issue only for these 2 variables.
MC year weight of year 1 (1) is always used : 

356 = 355.5 = (711 / 6) * 1 * 3

If you set a weight of 0 for year 1 , all values will be 0
