### ISSUE TITLE
Better performance for IO tasks

### ISSUE THREAD

**Issue by payetvin** [AntaresSimulatorTeam/Antares_Simulator#2105]
https://stackoverflow.com/a/2602060
If readfile is used to open large file it may good to improve the implementation.
An issue may be opened to talk about the subject

_Originally posted by @JasonMarechal25 in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/2066#discussion_r1601744460_

**Comment by flomnes** [comment]
It seems that we already resize the buffer according to the file size. See **src/ext/yuni/src/yuni/io/file/file.cpp**
```cpp
    Yuni::IO::File::Stream f(filename);
    if (not f.opened())
        return errNotFound;

    // retrieve the file size in bytes
    f.seekFromEndOfFile(0);
    uint64_t filesize = (uint64_t)f.tell();
// ..
    // resize the buffer accordingly
    out.resize((typename StringT::size_type)filesize);
    // replace the cursor within the file
    f.seekFromBeginning(0);

**Comment by pet-mit** [comment]
ANT-2142
