### ISSUE TITLE
Enabling the specification of several max generating power time-series for hydro reservoirs

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#213]
Today, in Antares, for a given area, only one time-series of maximum generating power can be specified for the hydro reservoir of this area, which is then used for all the simulated Monte-Carlo years. This is also the case for maximum pumping power and maximum generating and pumping energies time-series (see screenshot below).
![image](https://user-images.githubusercontent.com/53614116/113149598-8064a900-9233-11eb-8757-348580762809.png)

The requested enhancement is to allow to specify several maximum generating power time-series for a given reservoir of a given done (as it is the case for solar and wind power generation, for example). To build a given Monte-Carlo year, Antares would then select one of these time-series (either randomly or via a proper setting of the scenario builder).

This enhancement also requires GUI evolutions to provide the user with a table in which he can fill in several daily time-series of max generating power, one per column. It also requires an evolution in the scenario builder to enable the user to specify which time-series is to be considered for a given MC year.

**Comment by sgatto** [comment]
### Questions:
Q1: the scenario builder offers one choice for Hydro. It selects the TS of MaxGenPower with the same choices of  RunOfRiver end Hydro Storage. Is this OK ?

![image](https://user-images.githubusercontent.com/26088210/114151606-90f4dd80-991d-11eb-85f5-ea39be3771b6.png)


Q2: What should happen when the number of TS of GenMaxPower is different from the TS number for  ROR or HydroStorage ?

![image](https://user-images.githubusercontent.com/26088210/114151654-9fdb9000-991d-11eb-9d0f-ca94ed29abab.png)


Q3: what should we do with the MaxGenPower column in LocalData/DailyPower&EnergyCredits ?

![image](https://user-images.githubusercontent.com/26088210/114151720-b386f680-991d-11eb-977e-a7907513c753.png)

Q4: should we put the max gen power in the output? If so how?

Q5: how do we plan to treat the compatibility with previous versions? I.E. current Antares version has only one TS, should it be used to fill the TS-file of MaxGenPower of the future version?  This point can be very costly depending on how we deal with it.

### Changes
C1: The GUI a new tab MaxGenPower in Hydro/TimeSeries.

C2:

**Estimation ~ 6-8 manWeeks**

**Comment by PPlessiez** [comment]
Thanks for the estimates!

**Proposed answers**
Q1: Max gen power is only defined for storage, this is not taken into account for RoR (fatal generation).

Q2: Ideally, they should be independant (a different TS number can be chosen for storage inflows and for storage max power).

Q3: This should be removed to avoid confusion.

Q4: Not necessarily, it can stay in the input. To be discussed with end-users.

Q5: I would say that the suggested proposal is the cleanest one.
@sgatto Can you elaborate a bit on the complexity? Are there other "simpler" options?

**Comment by flomnes** [comment]
See #1723
