### ISSUE TITLE
Enabling the specification of several min generating power time-series for hydro reservoirs

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#214]
This request is similar to the request which was formulated in ticket #213: the need is to allow the user to specify several minimum generating power time-series for a given reservoir. To build a given Monte-Carlo year, Antares would then select one of these time-series (either randomly or via a proper setting of the scenario builder).

On top of the GUI/scenario builder evolutions that this enhancement requires (which are similar to the evolutions described in #213 ), an evolution of the optimisation problem is also needed: in the current problem formulation, no minimum generating power of hydro reservoirs is taken into account in the management constraints for hydro reservoirs.

**Comment by sgatto** [comment]
Observation of JeanMarc: 

> we could bring the optimisation problem back to what is done today and consider the  « Pmin(t) » as a must-run production and consider the pilotable part as « Pmax(t) – Pmin(t) »

I have some doubts:
It seems to me that the must-run Hydro-production impacts the reservoirs sot it is not a "simple" must-run production independent to the current hydro-prodution.

**Comment by PPlessiez** [comment]
Indeed, this decouples the minimum generation from the reservoir management, with the following consequences:
- This minimum generation is not taken into account in the reservoir trajectories (can be overcome by shifting the reservoir trajectories)
- It is not taken into account in hydro heuristics (can potentially be overcome by the shifting of reservoir trajectories, this is to be discussed with APG).
- It can lead to negative resulting inflows when Pmin > inflows for a given day

So some workarounds can provide a solution in the general case, but with some limitations/complexities.

**Comment by sgatto** [comment]
### Questions:
Q1: should the PMin be treated like the Pmax in the GUI?

Q2: what should be done when Pmin>inflows?

Q3: what should happen if Pmin puts the reservoir level outside the reservoir levels?

The Hydro management becomes over-specified with the risk of easily having unfeaseble problems.

### Estimation
difficult to estimate due to the lack of specification for the mathematical modelisation: i.e. special cases 

Some developpements can be mutualised with issue #213 

**over 8 man weeks** it depends on the specification related to the mathematical modelisation.

**Comment by PPlessiez** [comment]
Thanks for the estimate!

**Proposed answers:**
Q1: Ideally, yes, and they should be in the same table.

Q2: it is possible for a given day that 24*Pmin > inflows of the day (this is even a known case), no issue should be raised. If the sum of Pmin over the whole year is higher than the inflows, an error should be raised: to be discussed with end-users.

Q3: Respecting Pmin should be the priority, even if it means violating rule curves: to be further discussed with end-users.

**Comment by flomnes** [comment]
Done, see mingen (RTE-i contribution https://antares-simulator.readthedocs.io/en/latest/CHANGELOG/#new-features_2)
