### ISSUE TITLE
Results differ slightly when MPS are written with OR-Tools + XPRESS

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#2158]
How to reproduce ?
- Use OR-Tools + XPRESS
- Run a simulation without MPS export
- Run a simulation with MPS export (at least for the 1st weekly optimization)
- Results should be slightly different

This is probably caused by the fact that `MPSolver::Write` calls a `Reset` method for the XPRESS interface. A possible workaround is to use another instance of `MPSolver` to write problems.

**Comment by pet-mit** [comment]
ANT-2122
