### ISSUE TITLE
Feature wind off-shore (or miscellaneus renewable)

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#220]
This is a new feature about a new kind of renewable (could be called misc. renewable).
More accurately, we want to offer the possibility to add renewable clusters (of wind or solar type) to any area and provide many time series (or TS) to each renewable cluster. For each renewable cluster and a given year, the related ready-made TS number is chosen by the user or drawn randomly.
 
## Antares main Window
- A new tab is to be added in the main notebook, named Renewable (or misc. renewable). 
- This tab is built on the model of the Thermal tab : it contains an area selector and a possibility to **add**/**delete** (possibly **clone**) renewable clusters to any area.
- Once an area is selected (as well as a cluster), 3 frames must appear : 
   - the list of renewable clusters (**up**),
   - a minimal frame containing some characteristics of the selected cluster : name, type [wind or solar], area it belongs to (**left**)
   - a table containing a time series per column (**right**)

### "Old" and "New" renewables

The existent **Wind** and **Solar** tabs are kept as they are now. To avoid confusion, a toggle button is to be added to select between "old" and "new" renewable.

Old renewables allow TS generation, but only "Solar" and "Wind".

New renewables do not allow TS generation, but multiple types of solar & wind.

## Scenario builder
The scenario builder (choice of TS number for a year and a cluster) is similar to the thermal scenario builder.

## Input
A new directory is created in the **input** directory, called **renewables**, with the same structure as the **thermal** directory, except for the **prepro** subdirectory, nonexistant here.
We have to read the content of this directory when we load the study, and write it when some cluster data changed or when we make a **save as** operation. 

### Building outputs
Regarding the renewable clusters, there are 2 types of results : 
- The classical **Wind** and **Solar** results. These results can be found only in the result files whose names are "values" prefixed. To the classical results (the TS chosen randomly or by user), we need to add the TS chosen for the renewable clusters of the same type : for example, for a given area, we add to the **Wind** classical results, the chosen TS associated to all renewable clusters of type **Wind** in the area.
So we only have to make an addition to variable **Wind** and **Solar** before they are printed. Should be short and easy.
- A new kind of results : the details of each renewable clusters, as it is done for the thermal clusters. Of course, these results are based on the TS chosen before the simulation, whether they were chosen by user (via scenario builder) or randomly. 

### Reading outputs
- Tab **General values**
Reading these file is already done. Nothong to do.
- Tab **Renewable values**
This should be a new tab, close to the **Thermal plants** tab and similar to it : it contains the details of every renewable cluster.

## Solver
- Data structure : we provide a data structure to contain the production of each renewable cluster.
**Caution** : we may have to refactor the already existing cluster class, so that it contains a common part (parent class),  a  thermal cluster part (derived from the parent class), and a renewable cluster class (also derived from the parent class).
- In case the scenario builder is not used for any renewable cluster, we have to choose randomly which TS is associated to that cluster.
-  As it is already done for **Wind** and **Solar**,  we must substract from the load, the production of the renewable clusters

**Comment by guilpier-code** [comment]
For every item of the pull request (see this PR introducting comment), we give a cost. We add a **test** item.

Task | Time needed (days-per-man) | comments
------------ | ------------- | -----------
**Antares main Window** | 12 | Should not be difficult, as something similar already exists.
**Scenario builder** | 12 | something similar exists
**Input** | 8 | 
**Building outputs** | 7 |
**Reading outputs** | 5 |
**Solver** | 3 |
**Cluster refactoring** | 3 |
**Tests** | 5 |
**Total** | 55 |

**Comment by flomnes** [comment]
### Priorité fin mai : IHM
  Onglets "simulation" et "Renewable" (nouvel onglet)

## Brouillon

* Ajout d'une colonne dans l'onglet "Simulation"
   Griser les paramètres relatifs à la génération de séries (stochastic TS) de la colonne renewable
  "Intra" et "inter-modal" déjà pris en compte par le sc. builder dans le cas "custom"

* Ajout d'un écran de sélection des clusters renewable
  Ce qui est implémenté
   - Pas de nominal capacity => à implémenter ? Introduction d'une série de "capacity modulation"
   - Pas de unit count => à implémenter ?
   - Dans les séries temporelles, production horaire en MWh
   - On laisse de côté "Marg. cost modulation", "min gen modulation" (prepro ?)

Attributs d'un cluster
-	Son nom ; OK
-	Sa catégorie ; OK
-	Son nœud d’appartenance ; OK
-	S’il est en service ou non ; OK
-	Le nombre d’unités qu’il comporte ; A créer
-	La capacité de chaque unité ; A créer
-	La capacité installée (valeur calculée déduite du produit des 2 précédentes) ; A calculer à la volée

 (*)  Puissance générée(t) = Gen modulation(t) * Installed capacity
 Gen modulation provient des séries temporelles

 2 possibilités d'utilisation, au choix de l'utilisateur
 (1) Soit on met installed capacity = 1. Dans ce cas, les séries temporelles sont interprétées comme des puissances
 (2) Soit on met installed capacity = x MWh. Dans ce cas, les séries temporelles sont interprétées comme des facteurs de charge adimentionnels

 Par défaut, unit = 1, et nominal cap = 1, donc installed capacity = 1 * 1 = 1 : l'utilisateur peut mettre des puissances dans ses TS (cas d'utilisation (1)). On tombe sur le cas le + intuitif par défaut.

 Ajouter le pré-calcul de (*) : ajouter la multiplication des valeurs des séries par la capacité installée. A prendre en compte pour les données d'entrée du solveur et les outputs.
 
* Construction des scénarios : aucune différence par rapport au thermique

* Gestion des outputs
- Thematic trimming OK
- General values OK
- Ajouter l'équivalent de "thermal plants" et des fichiers "details-*.txt" pour chaque zone



* Création d'un switch
 - WS/Renewables/[WS+Renewables]
 - Impact IHM
 - Impact entrées-sorties
