### ISSUE TITLE
Adequacy, adding available production twice

### ISSUE THREAD

**Issue by payetvin** [AntaresSimulatorTeam/Antares_Simulator#2201]
src/solver/simulation/adequacy.cpp:438

Is it normal that the available production is added twice ?

_Originally posted by @payetvin in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/2168#discussion_r1650575405_

**Comment by payetvin** [comment]
@JMJ-rte

**Comment by payetvin** [comment]
Probably not normal, should be investigated and fix

**Comment by pet-mit** [comment]
ANT-2121
