### ISSUE TITLE
Launching Antares on Windows network drive

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [AntaresSimulatorTeam/Antares_Simulator#222]
**Description**
Antares Solver can not be launched on a Windows network drive

**How to Reproduce**
TBD

**Expected behavior**
Regular antares solver execution through CLI, but on a Windows network drive, or on a shared network folder (not mounted), using its address.

**Screenshots and additional files**
TBD

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8

**Additional context**
The calculations are to be launched on a Windows HPC cluster, using a SLURM script.

**Comment by flomnes** [comment]
Not our current priority. For reference, the issue was that Antares does not recognize "\\XXX\YYY\Z" as a valid file name.
