### ISSUE TITLE
Remove manual dynamic allocations

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#2244]
Dynamic allocations are considered vulnerabilities in our internal SonarCloud quality profile.

- 230 matches on `= new`
- 166 matches on `delete[]`
- 152 matches on `delete` (a few false positives)
- 2 matches on `malloc` and `free`

Some have already been replaced by `std::vector`. Other options include `std::shared_ptr` or `std::unique_ptr`.

**Comment by pet-mit** [comment]
ANT-2120
