### ISSUE TITLE
mingw compiler not supported (Windows)

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#2288]
Mostly due to low-level Yuni code.

![image](https://github.com/user-attachments/assets/2ba41f08-1d4d-44ca-8307-71f1ecdf12b5)

![image](https://github.com/user-attachments/assets/ae2924ba-111b-4f5b-b961-b5ade237ba35)

**Comment by pet-mit** [comment]
ANT-2185
