### ISSUE TITLE
Noises : updates and uses are messy

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#2297]
**Context** : 
Many production means ara supplied with noises to avoid execution instability and force a choice between weekly optimization's equivalent solutions.
In general, there's a noise a given year and area or each thermal clusters of an area. 
There are roughly 2 steps for every noise :
- **update** : for each year, area / clusters of an area, an update of the related noise is done
- **use** : then the noises are used to fill a field of the weekly optimization problem

**Problem** : lack of clarity and simplicity
- **Update** : instead of being done in one place, this update can be done in 2 different places. For instance, for thermal noises, a partial update is done before running a batch of parallel year (see function **computeRandomNumbers(...)**), and the rest inside a MC year (see function **PrepareRandomNumbers**). And the same for hydro noises.
- **Use** : we're filling the weekly problem with noises. Sometimes we do that inside a year, in function **PrepareRandomNumbers** (see for instance noises on un-supplied or spilled energy costs), and sometimes we do that in **BuildThermalPartOfWeeklyProblem** for thermal noises. Do we want it to be done like in different places depending on the production means ?

**Comment by pet-mit** [comment]
ANT-2183
