### ISSUE TITLE
Have sirius as optionnal for clients using Antares package

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#2301]
A client (i.e.) using find_package(Antares) is required to provide Sirius since sirius is a hard dependency
We should either provide the dependency (not just the .so but a way to resolve find_package(sirius_solver)) or relax the dependency on sirius

**Comment by flomnes** [comment]
Unfortunately, Sirius is now a strong dependency of Antares Simulator, see calls to `SPX_Simplexe` and `PI_Quamin`.

**Comment by pet-mit** [comment]
ANT-2182
