### ISSUE TITLE
Simplifying class OrtoolsMipVariable

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#2386]
We are currently forced to keep 2 lists of (**std::unique_ptr**) pointers :
- `variables_ `: pointer to **OrtoolsMipVariable**
- `constraints_ `: pointers to **OrtoolsMipConstraint**

These lists are required for member functions `addVariable(...)`,` getVariable(...,)` to return a raw pointer to **OrtoolsMipVariable** with respect to covariance related to base class **ILinearProblem** (same for constraints).
These lists are "copies" of **MPVariable** objects (resp. **MPConstraint**).

A subject could be to simplify code by removing these lists if we think they're not required.
To do that, instead of a raw pointer, these functions could return a freshly created std smart pointer.
We have the same thing for class **OrtoolsMipSolution**.

Possible issue : using smart pointers in that way may cause lower performances, so we should test it.

**Comment by pet-mit** [comment]
ANT-2109
