### ISSUE TITLE
Selection of nodes/units to re-run the TS generator

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#244]
**Description**
Request from Antares User club:  be able to select which nodes (or ideally units) in the cluster, we can re-run the TS generator; this would avoid overwriting all the timeseries. Concerns the TimeSeries generator.

**Current behaviour**
Today, when a user wants to generate thermal availability TS on a study, the TS are generated for all nodes and clusters. If the user wants to generate TS only for certain clusters, he has to copy-past the TS he doesn't need to change before running the TS generator, and paste them back in the study after the generation.

**Proposed enhancement**
The proposed enhancement consists in being able to choose for which nodes (or ideally, clusters) the TS generator should generate thermal TS before running it. For the other clusters, the TS which are already present would be unchanged.

**Comment by flomnes** [comment]
Duplicate with #361
