### ISSUE TITLE
Spillage & unsupplied costs stored in the wrong directory

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#252]
### Spillage & unsupplied costs stored in the wrong directory

Currently, each area has costs stored in folder **input/thermal/areas.ini**.

This information affects the termal modulation, but also the hydro optimization (pumping, etc.). I suggest moving this file to e.g **input/settings/inadequacy_costs.ini**.

Example of an **area.ini** file :
```ini
[unserverdenergycost]
east = 20000.000000
north = 20000.000000
south = 20000.000000
west = 20000.000000

[spilledenergycost]
```

**Comment by PPlessiez** [comment]
This requires evolutions in the data model, hence in the R packages used to edit them: this also needs to be planned with this enhancement.

**Comment by flomnes** [comment]
* Use **study-updater** to move files to the right place. This will make the study impossible to use with older versions of Antares.
* Update documentation

**Comment by JMJ-rte** [comment]
As discussed this morning, an old study should be analyzed with all the existing "analyzing tools" without being upgraded ("analyzing tools" are Antares output screens, R packages, ...).
An upgrade is required only if you have launched the new Antares release and you want to make additional simulations of your study.
Consequently, this means:
- Depending on the release used to generate your study, every "analyzing tool" should pick up the data of Spillage and ENS costs in the right directory ;
- Synchronization as to be done between the delivery of this feature in a new Antares version and all upgrades to be done in the different "analyzing tools" (especially R packages that are independent modules) ;
- An upgrade of a study that has a older release that the one selected to implement this feature, to a new release, induce the moving of the files from the old directory to the new one. It would be better to erase the files that were in the old directory than to duplicate them (which means a new kind of "deleting" function to implement into Antares)

**Comment by flomnes** [comment]
A better idea : **input/areas/<area>/optimization.ini**
```ini
[nodal optimization]
non-dispatchable-power = true
dispatchable-hydro-power = true
other-dispatchable-power = true
spread-unsupplied-energy-cost = 0.020000
spread-spilled-energy-cost = 0.000000
```
Move properties `unserverdenergycost` and `spilledenergycost` below.

**Comment by pet-mit** [comment]
ANT-2180
