### ISSUE TITLE
Created area is not appearing in Antares simulator

### ISSUE THREAD

**Issue by dmytrosmirnov** [AntaresSimulatorTeam/Antares_Simulator#274]
Dear Antares developers,
I have some problems regarding to the function  createArea(). 
When I  am trying to create an area in my Antares model, I have some problems.

opts <- antaresRead::setSimulationPath('NT2030_V802', simulation = 'input')
antaresEditObject::createArea(name='x_c3')

I am using such script to create it and it's working, it doesn't return me any errors, but when I go to my Antares model, I can't see any new areas if I go to the ,for example, tab Thermal in Antares simulator. How can I solve this problem?

Best regards,
Dmytro Smirnov

**Comment by PPlessiez** [comment]
Dear @dmytrosmirnov ,

I'm moving your issue to the following ticket (R packages github repo): [https://github.com/rte-antares-rpackage/antaresEditObject/issues/43](url)
