### ISSUE TITLE
Memory issue when running a study

### ISSUE THREAD

**Issue by AlexFauduet** [AntaresSimulatorTeam/Antares_Simulator#29]
When trying to run an Antares study, antares estimates a memory use of about 8GiB with more than 25GiB available (1st screenshot) but when actually running the simulation, it fails with the error message : not enough memory available (2nd screenshot).
Running the solver in swap mode doesn't solve the issue, with a new memory related error message (3rd screenshot).

**Caution : this issue cannot be reproduced on any computer**

![image](https://user-images.githubusercontent.com/44201771/91148153-89980100-e6b9-11ea-80ec-a10983063068.png)
![image](https://user-images.githubusercontent.com/44201771/91148271-b2b89180-e6b9-11ea-8531-e7b794c71190.png)
![image](https://user-images.githubusercontent.com/44201771/91148529-1216a180-e6ba-11ea-9b1a-e6f063edc904.png)

**Comment by jmkerloch** [comment]
Not reproducible
