### ISSUE TITLE
Crash when creating a thermal / renewable cluster

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#297]
**Description**
Crash when creating a thermal / renewable cluster in some situation

**How to Reproduce**
- Open a study containing clusters (thermal or renewable)
- Delete all clusters of an area
- Save the study
- Create a new cluster
- Crash occurs

**Expected behavior**
When creating the new cluster, Antares should not crash, it should create the cluster

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.0.0

**Comment by flomnes** [comment]
Also occurs on 8.0.3

**Comment by flomnes** [comment]
Fixed by #318
