### ISSUE TITLE
Hydro heuristic : what do we do with heuristic outputs ?

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#311]
**Context** : 
At the moment, it is possible to output some results regarding hydro heuristic.
It used to be done thanks to 2 pre-processing variables (**HYDRO_MONTHLY_SOLVER_DEBUG** and **HYDRO_DAILY_SOLVER_DEBUG**).
Now (in some development branch), we can do that by setting parameter **hydro-debug** to true.
This parameter cannot be set in the UI, but only manually in file **generaldata.ini**.

Question : 
Do we make this parameter available for users in the UI ?

**Comment by flomnes** [comment]
We probably don't want to do this, since it would expose unnecessary info to the user.

**Comment by flomnes** [comment]
We do not plan to display this parameter in the current GUI. Maybe AntaresWeb will have an "expert" panel with advanced options.
