### ISSUE TITLE
UI - renewable clusters : sorting cluster in a-z or z-a order does not work

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#322]
Context : 
In the GUI, thermal clusters (when there are several clusters in an area) can be sorted by their names,
either in the **A** to **Z** order, or in the **Z** to **A** order.
to do this, click on **a-z** button, or **z-a** button.

To be done : 
**a-z** or **z-a** buttons exist in renewable clusters panel, but cicking on them does not have any effect.
So make the sorting work.

**Comment by flomnes** [comment]
@guilpier-code : Can we close this ?

**Comment by guilpier-code** [comment]
Yes we can

**Comment by guilpier-code** [comment]
Eventually not a regression
