### ISSUE TITLE
CMAKE : useless library ?

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#325]
On one hand we have the **libantares-ui-component-htmllistbox** library.
On the other hand we have the bigger **libantares-ui-components** library, that includes the files that the previous library includes.
So the sames files are included in 2 libraries.
Is it normal or expected ? Or is it a wrong repetition ?

The problem is : 
if we change files in one library some day,
- we must change them in the other one.
- we could forget to add/change files in one of the 2 libraries

At least the common files should be gathered in a single cmake variable.
At best, one of the 2 lists of common files should be removed.

**Comment by flomnes** [comment]
It is possible that these files were compiled twice (or even more for the swap flavor...)
