### ISSUE TITLE
UI - Thermal/Renewable Clusters : extract common code

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#341]
In the GUI, first work to introduce the concept of renewable clusters lead to a code duplication from thermal clusters UI classes.
We have now to extract the common code from both thermal / renewable clusters UI classes.

All related files can be found in **src/ui/simulator**.
We only point files on the renewable side : 
- [x] FO - application/main/build/scenario-builder.cpp	:  1 class
- [x] toolbox/components/datagrid/renderer/area/renewable.areasummary.h	:  1 class
- [x] toolbox/components/datagrid/renderer/area/timeseries.h	: 1 class
- [ ] toolbox/components/datagrid/renderer/scenario-builder-renewable-renderer.h	:  1 class
- [x] toolbox/components/datagrid/renderer/ts-management-clusters-as-renewables.h	: 1 class
- [x] toolbox/components/htmllistbox/datasource/renewable-cluster.h	:  2 classes
- [x] toolbox/components/htmllistbox/item/renewable-cluster.h	: 1 class
- [ ] FO - toolbox/input/renewable-cluster.h	: 1 class
- [x] windows/inspector/property.update.cpp	:  1 function
		see _onPropertyChanging_<...>Clusters(...)_
- [ ] FO - windows/renewables/cluster.h	:  1 class
- [ ] FO - windows/renewables/panel.h	:  1 class

**Notice that** these files are associated to tag v8.1.0-rc3 in the repository.
They could have been renamed in the mean time, as well as classes they contained

**Comment by flomnes** [comment]
Tag has been fixed
