### ISSUE TITLE
Traitement différent entre BC skipped et BC disabled

### ISSUE THREAD

**Issue by JMJ-rte** [AntaresSimulatorTeam/Antares_Simulator#355]
**Description**
Le fait qu'une contrainte couplante soit "skipped" (associées à des clusters tous désactivés par exemple) ne supprime pas totalement le test de vraisemblance de la contrainte sur la première semaine.
Ainsi, si une contrainte couplante est de type : "1.00 x cluster1 + 1.00 x cluster2 > b" et que b est strictement positif sur la première semaine alors le test de vraisemblance si cluster1 et cluster2 sont désactivés, dit qu'il est impossible que 0 + 0 > b et la simulation sort en erreur

**How to Reproduce**
Etude simple pour reproduire l'anomalie 
[test.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/7014804/test.zip)

**Expected behavior**
Supprimer tout test de vraisemblance lorsqu'une contrainte couplante est de type "skipped" (la traiter comme si elle était "disabled").

**Screenshots and additional files**
If applicable, add screenshots to help explain your problem. You may also include a .zip file containing your study.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.0.* branch

**Additional context**

**Comment by flomnes** [comment]
Il existe une solution de contournement : désactiver toutes les contraintes concernées à la main.

**Comment by flomnes** [comment]
Info is generated on-the-fly in the GUI. The solver should have access to it to disable the corresponding binding constraint.

GUI source file : **src/ui/simulator/toolbox/components/datagrid/renderer/bindingconstraint/weights.cpp**

Solver source file : **src/libs/antares/study/runtime/runtime.cpp**

**Comment by flomnes** [comment]
PR #366 allows to successfully run the provided test-case when an unfeasible BC is marked as skipped, that is **skip binding constraints which are marked as skipped**.
