### ISSUE TITLE
AntaresEditObject Thermal Timeseries Generation did not work

### ISSUE THREAD

**Issue by ThanhEGI** [AntaresSimulatorTeam/Antares_Simulator#356]
**Description**
I use the package AntaresEditObject in order to edit my Antares model via RStudio. When I tried to let the thermal timeseries automatically generated, it did not work. Therefore, there were no thermalavailabilities Timeseries in the input folder, which can be read.

**How to Reproduce**
In Rstudio, I put the following command to start the timeseries generator for my thermal plant fleet.
  updateGeneralSettings(generate = c("thermal"))
  updateInputSettings(import = "thermal")
  runTsGenerator(path_solver = "C:/Program Files/RTE/Antares/7.1.0/bin/antares-7.1-solver.exe")
When looking into my input > thermal > series > area 1 > Power Plant 1, the series.txt file is empty and do not have the number of timeseries I wanted to generate. There is obviously an error in the Timeseries generator in Antares.

Afterwards, when I try to read the thermal availabilities timeseries, I get an error:
Function: thermal_ts = readInputTS(thermalAvailabilities = "all")
Error: Error in .checkTypos(e, names_x) : Object 'cluster' not found amongst 
In addition: Warning message:
In .addOutputToRes("thermalAvailabilities", thermalAvailabilities,  :
 
**Expected behavior**
Can you please help me to check why the timeseries generator did not work in my case? One month ago, I used the same script and it worked. 

**Screenshots and additional files**
If applicable, add screenshots to help explain your problem. You may also include a .zip file containing your study.

**OS and version**
 - OS: windows
 - Antares Simulator version: 7.1

**Additional context**

**Comment by flomnes** [comment]
@PPlessiez Can you move this issue about R packages to the right place ?

**Comment by PPlessiez** [comment]
Dear @ThanhEGI,
I just moved the issue to the antaresEditObject github repo (issue [here](https://github.com/rte-antares-rpackage/antaresEditObject/issues/46)), and I'm closing this one.
