### ISSUE TITLE
Allow to enable/disable TS generation for specific thermal clusters

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#361]
Currently, there is only a **global** parameter for enabling/disabling TS generation for thermal clusters : `parameters.timeSeriesToGenerate & timeSeriesThermal`.

However, in some cases, the user wants to keep their ready-made TS for some clusters, and generate TS for other clusters.

Allow the user to fine-tune this behavior by adding a **local** parameter, i.e one parameter per cluster.

**Comment by flomnes** [comment]
PR #357 partially satisfies this request by allowing the user to disable TS generation for some clusters when it is enabled globally (A).

The inverse is not true : the user cannot enable TS generation for some clusters when it disabled globally (B).

Default values for the local parameter are a problem : they do not allow both items A & B above. One way to deal with this is to introduce a 3rd value for the global parameter : 
- Enable TS gen for all clusters
- Disable TS gen for all clusters
- Mixed : use local parameter for each cluster

To make the 3rd option convenient, one would need a way to turn on/off all clusters at once.

**Comment by flomnes** [comment]
Another way is to give the local parameter a different meaning : "invert the global parameter for this cluster".

This way we can set the default value for the local parameter to "false". 

I find this design confusing for the user. But the implementation is almost immediate, unlike the previous idea.

**Comment by JMJ-rte** [comment]
No, I do not like the idea, because when a user will disabled globally, I will not expect that the clusters that were already declared as desabled become enabled.
So 2 parameters are potentially required by cluster to forced specifically for this cluster the fact that it is enabled or disabled, independently of what was set globally.

**Comment by flomnes** [comment]
As discussed with @JMJ-rte, the retained solution is the following :

For each cluster, introduce a local parameter that can take 3 values :
- Use global parameter (default)
- Force generation, overriding the global parameter
- Force no generation, overriding the global parameter

**Comment by flomnes** [comment]
[Relevant study](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/7059881/gen_ts.zip)

One cluster of each kind (force gen, force no gen, use global), 3 MC years. Test whether TS are generated depending on the selected parameter for each cluster.

**Comment by flomnes** [comment]
Implemented in v8.2
