### ISSUE TITLE
Improve the study cleaner functionalities

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#369]
When deleting elements in an Antares study via a script (e.g. an area), the deletion can sometimes be incomplete (e.g. the area is not removed from all the files in which it appears).
This can lead to complex situations in which an area does not appear in Antares GUI and in the results, but still has an influence on the results of neighboring areas, which are then incorrect. In these cases, it appears that the study cleaner function is imperfect as it does not detect all the remaining elements to be removed.

The proposed evolution is to improve the study cleaner functionalities so it can deal with incomplete removal of elements and ensure that the study is fully cleaned after the execution of the functionality.

**Comment by flomnes** [comment]
@PPlessiez can you be more specific ? Do you have an example at hand ?
