### ISSUE TITLE
Crash in hydro heuristic when preparing net demand

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#374]
**Description**
A crash occurs on a study, in the hydro heuristic, when preparing net demand.
The study's renewable policy is **Aggregated**.
See cause of the crash further. 

**How to Reproduce**
See attached study zip file.
[Four areas - renewable-not-enough-TS-for-inter-modal.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/7134730/Four.areas.-.renewable-not-enough-TS-for-inter-modal.zip)

**OS and version**
 - OS: [e.g. Windows, GNU/Linux]
 - Antares Simulator version: 8.1.0rc3

**Cause of the crash**
In **src\solver\hydro\management\management.cpp**, the **net demand** computation involves the **wind** time series.
In renewable mode **Aggregated**, **wind** time series are not supposed to be involved in the computation.
In this case, **wind** time series is never allocated, so the **wind** TS table is totally empty because : 
- **wind** time series are generated TS kind.
- **Aggregated** mode for renewable prevents from allocating (and generating) the wind TS table.

**Comment by flomnes** [comment]
See #371
