### ISSUE TITLE
Modelling CCGT and GT operating in Open Cycle by using binding constraints

### ISSUE THREAD

**Issue by ThanhEGI** [AntaresSimulatorTeam/Antares_Simulator#378]
Hi guys,
I am seeking for help in modelling CCGT in ANTARES, especially defining linear binding constraint. 
CCGT consists of Steam Turbine (ST) and the Gas Turbines (GT). Let's assume that the CCGT block is based on one ST and 4 GTs. The ST operation is dependent from the GT's operation because it uses the heat to create Steam and produce electricity. However, the Gas Turbine can still operate independently in the so-called open cycle. Therefore, we should have two relevant operation mode:
1. GTs operating in open cycle.
2. ST and GTs operating together in a block.
I can combine the technical parameter of the GTs and STs and define the CCGT as one power plant in ANTARES. Additionally, the GTs will also exist in ANTARES. I would need to have a binding constraint which prevent the dispatch of both plants CCGT and GT in open cycle. 
Did anyone has experience with the modelling of CCGT and the implementation of such binding constraints in ANTARES where I cannot impose any Binary Variable.
Thanks!

**Comment by payetvin** [comment]
Will be done in Andromede modeller
