### ISSUE TITLE
Doc install : running unit tests

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#397]
If you wish to run unit tests,  the doc **INSTALL-windows.md** says to run command : 
**ctest -C Release --output-on-failure -L units**

This does not work, the following cmd should be run instead : 
**ctest -C Release --output-on-failure -L unit**

Please change the tests options table in the doc as well.

**Comment by a-zakir** [comment]
-R instead of -L
