### ISSUE TITLE
Log report window for some study

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#398]
For study **MAF2025**, log report contains very large lines.
![study-log-report](https://user-images.githubusercontent.com/62292552/135484481-6b22336b-b247-4813-964c-f4bad24d4792.PNG)

There are 2 things we should enhance : 
- we should shorten the larges lines (no need for them to be shown thouroughly, as they can be found in the log file)
- the vertical scrolling is very slow (see if it is caused by the large lines that must be often refreshed or not)

Study can be found here : 
[case study.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/7260744/case.study.zip)

**Comment by flomnes** [comment]
@guilpier-code If you want to reproduce the issue without having to run the case study for 30 minutes, you can add logs with something like this
```cpp
for (uint ii = 0; ii < 1000; ++ii)
    logs.warning() << "Lorem ipsum";
```

and run a simple study instead. This will save you a lot of time.

**Comment by flomnes** [comment]
See **rules.cpp**. Limit that loop to 10 iterations
```cpp
for (; itv != scenariiForCurrentCluster.end(); itv++)
```

**Comment by flomnes** [comment]
Vertical scrolling speed is now OK. However it would be nice to have an horizontal scroll / resizable window.
