### ISSUE TITLE
Correct/update reference guide

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/Antares_Simulator#403]
The new markdown version of th doc should be updated.

In the branch `doc` a draft version of the reference guide is present and an old markdown version 7.2. They are both not shown in the Mkdocs website.

- [ ] update the reference guide
- [ ] add a chapter to mkdocs.yml
- [ ] change the index file of the sphinx documentation (used to produce the pdf reference guide file)
- [ ] update if necessary the github action used to produce the pdf

**Comment by flomnes** [comment]
Done ! Thanks @sgatto
