### ISSUE TITLE
Spacial Correlation math functions applied twice

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [AntaresSimulatorTeam/Antares_Simulator#405]
**Description**
In all the windows where you can input a Spatial Correlation (Load, Hydro, Wind & Solar), using a mathematical function +, -, *, /, will result in the function being applied twice. Example: I have a correlation of 10% that I multiply by 3, I will end up with 90%.

**How to Reproduce**
- Start with an empty study
- Add 2 nodes
- Go in any of Load/Hydro/Wind or Solar's correlation window
- Click a non-diagonal value of the matrix (which is 0 by default)
- Value + 10  and Apply will result in a 20 shown in the matrix

**Expected behavior**
The operation should be carried out only once.

**Screenshots and additional files**
![image](https://user-images.githubusercontent.com/73881097/136429706-7a48ae4d-ed78-42a0-819f-f6edca02e8ff.png)

**OS and version**
 - OS: Linux
 - Antares Simulator version: 8.1

**Comment by flomnes** [comment]
# Context
The matrix must be symmetric ie Corr_{i, j} = Corr_{j, i} for all i,j.

Whenever you change a value in this matrix, there are two cases:
1. It is in the diagonal : i == j. Nothing to do
2. It is not in the diagonal : i != j. Then you must update also the term j,i to make sure the matrix remains symmetric.

# Diagnosis
This procedure works when you edit individual values. But if fails when you update multiple (e.g all) values simultaneously. In this case, the following happens:
1. Cell i,j is updated
2. This triggers the update of cell j,i. So far, so good
3. Cell j,i is updated once again. This is what causes your problem
4. This triggers the update of cell i,j. Same problem

# Possible fix (to be discussed)
We could update all cell value, then make sure that the matrix remains symmetric by applying this operation:
M_new = (M + M^T)/2

I'm not sure that this would update values properly ins all cases. For example, if the user only wants to update row j, this formula updates row j and column j, which probably isn't the intended behavior.

**Comment by hugo-antoine-rtei** [comment]
From over here, it looks like an easier option would be to make half (either upper or lower diagonal) of the matrix unmodifiable, or to even not show it. I don't know if it is actually easier, but maybe it is something to consider ?

**Comment by flomnes** [comment]
@hugo-antoine-rtei I agree. However I believe that this table is represented by a generic class. We may have to use a specialized class instead to enforce these constraints.
