### ISSUE TITLE
add NSIS log as artifact to action 

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/Antares_Simulator#418]
CMake install is responsible to create a Windows installer using NSIS.
If the NSIS generator fails the errors are written to a file.
If the Action fails no information can be retrieved from the NSIS log file if the logfile is not provided as an artifact.

We should add the NSIS logfile as an artifact of the widwos actions

**Comment by flomnes** [comment]
This would be useful : I once encountered hard-to-debug errors in the installer creation phase with NSIS. The problem is that if the creation step fails, no subsequent step is executed, including the upload of NSIS's logs.

**Comment by flomnes** [comment]
Done in 8.3-rc2. Logs are uploaded as artifacts in case of failure.
