### ISSUE TITLE
intra-modal width check is too restrictive

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#442]
If intra-modal correlation is enabled, we should check that all matrices have the same width, but some of them could be of width 1.

Currently, we ignore matrices of width 1.

@PPlessiez Is it the same with **inter**-modal correlation ?

**Comment by PPlessiez** [comment]
Yes, except that:
- For intra-modal correlation, for **any** category (load, solar, wind...) where it is activated, we check that in **all** the nodes of the study, the matrices of this category have either the same number of columns or one.
- For inter-modal correlation, for **all** the categories where it is activated, we check that in **any** node of the study, the matrices of all these categories have either the same number of columns or one.

**Comment by guilpier-code** [comment]
- construire ne structure de données qui contienne le nombre de TS pour chaque zone et chaque mode (solaire, éolien, etc.).
- Intra-modal : ignorer les 1 lors de l'étape de vérification
- Intra-modal : ignorer les 1 lors de l'étape de tirage
- inter-modal : ignorer les 1 lors de l'étape **applyMatrixDrawsToInterModalModesInArea**

**Comment by flomnes** [comment]
I agree that we need a refactor to better separate responsibilities. I have identified several classes/functions.

1. Get the number of time-series for a mode & an area. This function/class would be very useful both for checking consistency, for drawing TS numbers and choosing to store them or not. It would be separate from intra-modal checks.
2. One class/function to check intra-modal consistency
3. One class/function to check inter-modal consistency
4. One class/function to draw intra-modal TS numbers
5. One class/function to draw non-intra-modal TS numbers
6. One class/function to draw inter-modal TS numbers
