### ISSUE TITLE
How is the initial reservoir level handled when water values are used and one single week is run?

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#443]
For a given hydro reservoir, when we want to run a simulation on only one week in the middle of the year:

- When the reservoir is managed in heuristics mode, the heuristic hydro pre-allocation still occurs, and it fixes the reservoir levels at the beginning and the end of each week, so Antares knows what is the reservoir level at the beginning of the week which is simulated.

- When the reservoir is managed with water values, Antares has no way to know in advance the initial reservoir level of the simulated week without solving the previous weeks. Then I guess that the initial level of the simulated week is somehow randomly drawn between the low and high rule curves at the beginning of the week. Can you confirm that this is the case?

**Comment by flomnes** [comment]
Obviously, Antares Simulator cannot guess the initial reservoir level. If we wanted to obtain the same results no matter when we start in the year, all previous weeks should be simulated. This is probably not what is done.

The hydro code is quite hard to read. However, it seems that montlhy & daily credit modulation is called no matter the value of `useHeuristicTarget`, `useWaterValue`.

The only notable impact of `useWaterValue` is the following:
```cpp
            if (area.hydro.useWaterValue)
            {
                Antares::Data::getWaterValue(
                  problem.previousSimulationFinalLevel[k] * 100 / area.hydro.reservoirCapacity,
                  area.hydro.waterValues,
                  weekFirstDay,
                  state.h2oValueWorkVars,
                  problem.CaracteristiquesHydrauliques[k]->WeeklyWaterValueStateRegular);
            }
```
**src/solver/simulation/sim_calcul_economique.cpp**, function `SIM_RenseignementProblemeHebdo`.

The only notable impact of `useHeuristicTarget` is the way "DTG" is computed (**src/solver/hydro/management/daily.cpp**, l. 123), whether the computation of hydro levels is done before or after the "Hydro Remix" (**src/solver/simulation/common-hydro-levels.cpp**, l. 57 and callers). It is also used to define `problem.CaracteristiquesHydrauliques[i]->SuiviNiveauHoraire` and `problem.CaracteristiquesHydrauliques[i]->TurbinageEntreBornes` as well as variables `problem.CaracteristiquesHydrauliques[k]->MaxEnergieHydrauParIntervalleOptimise[j]` and `                            problem.CaracteristiquesHydrauliques[k]->MinEnergieHydrauParIntervalleOptimise[j]`.

It is unclear how `problem.CaracteristiquesHydrauliques[index]->NiveauInitialReservoir` is set or used.
