### ISSUE TITLE
Built Antares uses locally installed antares solver

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [AntaresSimulatorTeam/Antares_Simulator#480]
**Description**
Probably not an major issue, as this is mostly about convenience. If I really want to use the built solver, I can uninstall antares.

If you have installed Antares on your machine. And afterwards, you build another version of Antares, launch a GUI session through the _build_name/ui/simulator/antares-8.1-ui-simulator_ file. Then, the solver used on this session won't be the built one, but the installed one.

**How to Reproduce**
- Install antares 8.1
- build the antares on the branch https://github.com/AntaresSimulatorTeam/Antares_Simulator/tree/feature/thermal-ts-gen-switch
- open the built antares `./antares-8.1-ui-simulator`
- start an empty study, add an area, a thermal cluster, and put its _Generate TS_ parameter to _Force Generation_
- Run it
- You will get the following error, which doesn't trigger when actually using the solver of the built antares.

> \`new cluster\`/\`gen-ts\`: The property is unknown and ignored

**Expected behavior**
The built antares to use the built solver.

**Screenshots and additional files**
The logs of the failed simulation, where the solver used was in /usr/bin
[solver-20211208-190845.log](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/7678044/solver-20211208-190845.log)

**OS and version**
 - OS: Ubuntu 20.04.3
 - Antares Simulator version: 8.1 & branch feature/thermal-ts-gen-switch

**Comment by flomnes** [comment]
The solver that is used is the one installed on your system (directory /usr/bin/). We should use the built version instead.

See file **src/libs/antares/solver.cpp** 
```cpp
    else
    {
        searchpaths.directories.push_back(s.clear() << "/usr/local/bin/");
        searchpaths.directories.push_back(s.clear() << "/usr/bin/");
        searchpaths.directories.push_back((s = root) << "/../../solver");
        searchpaths.directories.push_back(root); // TGZ package
    }
```
/usr/bin (system solver) is searched before ../../solver (built solver). The built version should be the 1st in the search list.
