### ISSUE TITLE
split onshore and offshore wind profiles in antares

### ISSUE THREAD

**Issue by jorritvm** [AntaresSimulatorTeam/Antares_Simulator#5]
Antares requires the user to enter wind as a single category for each area. If the user want's to separate wind output in onshore & offshore wind farms he has to create virtual areas. 

We often work with very big models (> 200 areas) for which this solution is undesired. It would be nice if a separate input option was available per area.

Could this be added to the roadmap?

**Comment by flomnes** [comment]
Thank you for your suggestion. The split was added to the roadmap.

See #220 for a technical discussion.
