### ISSUE TITLE
UI 7.1 crashes when selecting a specific dependency in the inspector

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/Antares_Simulator#50]
I am running Antares v7.1
I just tried to change the selection of the "dependencies" of one area in the "inspector" tab.
As soon as I try to change the value selecting one specific link or one specific cluster Antares crashes.
The Antares study I am using is very small
[STA-mini.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/5238846/STA-mini.zip)

**Comment by jmkerloch** [comment]
This issue comes from wxWidgets management of popup menu in the inspector component.
In the case of no item available in popup menu or if user doesn't click on on of the item, wxWidgets always call the same callback and we go in an infinite loop.

**Comment by jmkerloch** [comment]
Feature selection of the "dependencies" from the "inspector" tab must be disabled.
Feature of selection should be specified in a new issue.
