### ISSUE TITLE
matrix.hxx is compiled 1241 times

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#553]
Consider moving some code to a .cpp file.

**Comment by flomnes** [comment]
- 2nd template parameter is only used for I/O
- UI has a strong dependency on Matrix
- Possible solution : [explicit instanciation](https://www.ibm.com/docs/ro/i/7.5?topic=only-explicit-instantiation-c)

**Comment by pet-mit** [comment]
ANT-2141
