### ISSUE TITLE
Antares V8.2-rc1 - the selected link is unselected when saving the study

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#564]
**Description**
When a link is selected via the GUI and the study is saved, the link is then unselected.
Note: this issue already exists in V8.1.

**How to Reproduce**
Select a link in the study via the GUI, then save the study -> the link will be unselected.

**Expected behavior**
Keep the link selection when saving.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2-rc1

**Comment by flomnes** [comment]
Bug is confirmed. Will try to fix in 8.2

**Comment by flomnes** [comment]
It is also the case for thermal/renewable clusters. It is not the case for areas though.
