### ISSUE TITLE
Antares V8.2-rc1 - loop flows are highlighted in red in too many cases

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#565]
**Description**
For a given timestamp, the loop flow value which is set by the user is highlighted in red in the GUI whenever for any transmission capacities time-series, the inequality -transmission capacity indirect <= loop flow <= transmission capacity direct is not verified.

**Expected behavior**
This highlight seems too restrictive as not all Time-Series will necessarily be used in the simulation. Having an orange highlight seems sufficient, as long as the inequality check mentioned in the description is clearly checked within the optimization step.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2-rc1

**Comment by flomnes** [comment]
Not mutually exclusive
### Proposal 1
Highlight invalid loop-flow values in orange

### Proposal 2
If loop-flow is enabled, highlight the NTC cells that violate the loop-flow condition in orange

**Comment by PPlessiez** [comment]
Having the two would be perfect (only proposal 2 would be a bit strange as it might be hard for the user to understand exactly what is wrong with the NTC values)

**Comment by flomnes** [comment]
Here's a first try

## Transmission capacities
![image](https://user-images.githubusercontent.com/26088210/155112961-eff6bfaf-7a03-470a-9fd3-d09eba4fb1c4.png)
## Parameters
![image](https://user-images.githubusercontent.com/26088210/155113026-5b015c55-0bf6-4e06-874e-b920de4f163e.png)

Does that look good to you @PPlessiez ?
