### ISSUE TITLE
Antares V8.2-rc1 - Global link parameters not refreshed in GUI

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#566]
**Description**
In the GUI, when a global link parameter (use of transmission capacities, hurdle costs, asset type...) is changed in one of the "Parameters"/"Transmission capacities" tabs, the change is not reflected in the other tab unless the study is saved.

**Expected behavior**
When one of the parameters is changed in one of the "Parameters"/"Transmission capacities" tabs, the change should be visible in the other tab without having to save the study.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2-rc1

**Comment by flomnes** [comment]
Bug is confirmed.

@guilpier-code There seems to be a few missing refreshes.
