### ISSUE TITLE
Antares V8.2-rc1 - Infinite NTCs are not taken into account in the calculation

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#567]
**Description**
In the attached study, NTC are set as infinite in the unique link represented. However, in the results, it seems like this is not taken into account, and the NTC values from the Time-Series are used. This is true when NTC are set to infinite locally or as a global parameter of the study.

**How to Reproduce**
See attached study.

**Expected behavior**
When NTCs are set to infinite, there should be no restriction on the maximum flow on the corresponding link.

**Screenshots and additional files**
[study_ntc_example.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8110111/study_ntc_example.zip)

**OS and version**
 - OS: [e.g. Windows, GNU/Linux]
 - Antares Simulator version: [e.g. 6, 7.2, 8]

**Additional context**

**Comment by flomnes** [comment]
Bug is confirmed. Fix #568
