### ISSUE TITLE
Transmission capacities as a global (optimization) preference

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#573]
Suppose that the global preference **Transmission capacities** (go to **Configure > Optimization preferences**) is set to a value other than **Local values** (default). For instance **Set to null**.
Suppose that the study is new to the user, who does not know about the value of this global preference.
This user only knows about the local values (for each link), and so she could be misled by the simulation results

**Comment by flomnes** [comment]
Tell AntaresWeb devs to display a summary of possibly misleading parameters befure running a simulation

**Comment by flomnes** [comment]
@flomnes Check availability in AntaresWeb
