### ISSUE TITLE
Antares V8.2-rc2 - Incorrect TS numbers in the ts-numbers output directory

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#587]
**Description**
In the attached study containing 2 links, there is only one Time-Series for the link area-area 3, and the scenario builder NTC TS are set at random for the 4 MC years of the study.
However, when running a simulation, the ts-numbers output directory contains the following vector for the area - area 3 link: (4, 4, 2, 3).

**Expected behavior**
The ts-numbers output text files should contain only TS numbers corresponding to the input TS numbers for a given links (in this specific case, (1, 1, 1, 1)).

**Screenshots and additional files**
[Initial_study_for_datastorm.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8196045/Initial_study_for_datastorm.zip)

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2-RC2

**Comment by flomnes** [comment]
The problem is rather for area - area 3, that only has one TS. The ts-numbers should be (1,1,1,1), not (4,4,2,3).

**Comment by flomnes** [comment]
intermodal=true

**Comment by flomnes** [comment]
This is an old bug : it also applies to load, thermal, wind, solar, etc. I suggested a fix.
