### ISSUE TITLE
OrTools : Antares build with ortools stable version 

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#59]
OrTools is downloaded, built and installed during cmake configuration step.
By default, an Rte OrTools version is used. On demand (still at cmake configure step), last stable version can be used instead.
This latter option requires the download of an archive **scip-7.0.1.tgz** (not required by the default orTools), which is then unzipped.
On some Rte computers, this unzip operation goes wrong, stops the cmake configure step and prevents orTools from being installed.

**Comment by jmkerloch** [comment]
We will always use a RTE branch with sirius support. Closing issue.
