### ISSUE TITLE
Ubuntu : font error warning when opening a study saved in Windows

### ISSUE THREAD

**Issue by GoubetClem** [AntaresSimulatorTeam/Antares_Simulator#599]
**Description**
Warning message when opening of a Window version study save on Antares Ubuntu.

**How to Reproduce**
Open study from the RTE training session ANTA
If clicking on continue, does not seem to disturb the functionalities in the study.

**Expected behavior**
N.A.

**OS and version**
 - Linux Ubuntu 20.4
 - Antares Simulator version: 8.2 (.deb build)

**Additional context**

![Capture d’écran de 2022-03-15 14-01-55](https://user-images.githubusercontent.com/50197757/158383485-83007ca7-ff77-4086-aeb9-8c755c466a12.png)

**Comment by flomnes** [comment]
Can you attach the full backtrace and a .zip containing the study ?

**Comment by GoubetClem** [comment]
Here the files
[CaseTimeSeries_v8.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8255204/CaseTimeSeries_v8.zip)
[backtrace_antares.txt](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8255210/backtrace_antares.txt)

**Comment by flomnes** [comment]
Can't reproduce
