### ISSUE TITLE
Copy the entire matrix with styles (HTML) do only values copy

### ISSUE THREAD

**Issue by GoubetClem** [AntaresSimulatorTeam/Antares_Simulator#602]
**Description**
When chose to copy a table with the function "Copy the entire matrix with styles (HTML)" or save in .txt file or select all+ctrlC, do not copy the index or the columns name.

**How to Reproduce**
In study, for whatever table, do copy

**Expected behavior**
expected columns name and table index included in copy. These items can not be selected
[matrix.txt](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8261567/matrix.txt)

**Screenshots and additional files**
If applicable, add screenshots to help explain your problem. You may also include a .zip file containing your study.

**OS and version**
 - Linux Ubuntu 20.4
 - Antares Simulator version: 8.2

**Additional context**

**Comment by flomnes** [comment]
Thanks for the feedback. My understanding is that you want to have column names in your copy ? In this example, day, month, hour,...
![image](https://user-images.githubusercontent.com/26088210/158592789-b9611729-5cd9-4317-821b-158c739270e3.png)

It may or may not be desirable, depending on what you want to do. To be discussed with the Antares Team.

**Comment by GoubetClem** [comment]
Yes, I want the columns names (day, month etc.) and the index (01 JAN 00:00, 01 JAN 01:00 etc.) I cannot copy presently.

The Window version of my colleagues includes these items when copying.

**Comment by flomnes** [comment]
Ok then this is not a **bug report**, more of a **feature request**.

**Comment by GoubetClem** [comment]
It depends, we kind of expect that with the option "Copy the entire matrix with styles (HTML)" :-)

**Comment by flomnes** [comment]
I replied before you added that to your answer

> The Window version of my colleagues includes these items when copying.

Therefore I agree that this a bug. I'll investigate but I'm afraid the difference comes from the wxWidgets, which we cannot change.
