### ISSUE TITLE
[Antares V8.2] Output log screen not adjusted to screen width

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#613]
**Description**
When an Antares study is completed, the output pop-up screen is displayed showing the possible warnings/errors. In case the size of a warning is very large, the width of the pop-up is adjusted so this message can be displayed entirely. It is then very inconvenient to slide the pop-up to be able to reach the "Continue" button at the bottom-right, or to be able to read the message. It would be more appropriate to adapt the size of this screen to the width of the user screen.

**How to Reproduce**
Output pop-up log screen in case there is a long warning message (e.g. many areas with incorrect scenario builder configuration, which happens a lot in studies for which many areas are virtual areas).

**Expected behavior**
It would be more user-friendly to adapt the size of the log screen to the user screen rather than to the length of messages/

**Screenshots and additional files**
Example of a log screen output:
![screenshot_log_screen](https://user-images.githubusercontent.com/53614116/159661066-0adca749-69a3-4f5d-8ead-00888c3c898e.png)

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2 (but the issue already exists in previous versions)

**Comment by flomnes** [comment]
@PPlessiez Can you post a .zip containing the study ?

**Comment by PPlessiez** [comment]
Here is an example of a study where the problem occurs:
https://postngo.rte-france.com/?lang=fr&a=d&i=uaRMclSRJAbtvjy5G0IF

**Comment by guilpier-code** [comment]
Thanks Paul, but wow ! Big study ! :-)
