### ISSUE TITLE
[Antares V8.2] Hot start - too restrictive check on initialization month 

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#615]
**Description**
When the hot start mode is activated for reservoirs in Antares, one of the initial checks performed before launching the study is to check that for all reservoirs, the initial reservoir level is fixed on the same month as the first month of the study.
This check makes sense for reservoirs for which the reservoir management mode is activated, but it is useless to check it for reservoirs not being in reservoir management mode (which do not have a reservoir level follow-up and are not concerned by the hot start).

**How to Reproduce**
Have an Antares study in hot start mode with some reservoirs without reservoir management and for which the month to initialize the reservoir level is different from the first month of the study.

**Expected behavior**
For reservoirs without reservoir management, this check shouldn't be performed.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2

**Comment by flomnes** [comment]
@PPlessiez Can you post the error message here please ?

**Comment by PPlessiez** [comment]
Here is the error message issued after a failed check of reservoir initialization months.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/53614116/160580307-fb821063-d040-4885-991e-36cf33db847c.png)

**Comment by PPlessiez** [comment]
In the study below with two DE and FR areas, the check for hot start is performed for both reservoirs, and it fails because the initialization month for DE reservoir is different from the first month of the study.
However, as reservoir management is not activated for DE reservoir, hot start is not applied anyway to this reservoir, so the check on the initialization month should ignore it.

[BP50_M23_CC1_Xeq_simplified.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8370402/BP50_M23_CC1_Xeq_simplified.zip)
