### ISSUE TITLE
[Antares V8.2] Check on FO/PO duration is performed even if thermal TS are ready-made

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#616]
**Description**
When an Antares simulation is launched, Antares checks if the FO/PO durations are realistic (> 0).  This check is performed even when the thermal TS are set to "ready-made", which is not useful as these parameters will not be used.

**How to Reproduce**
Launch an Antares simulation with FO/PO durations equal to 0 for some clusters, and thermal TS status set to "ready-made".

**Expected behavior**
The FO/PO duration consistency check should not be performed for thermal clusters for which no thermal TS will be generated.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2

**Comment by flomnes** [comment]
Requires quite a large refactor, I'm afraid.

**Comment by PPlessiez** [comment]
This is the displayed error message:

![image](https://user-images.githubusercontent.com/53614116/160164630-c58ff743-39a3-4c12-8bde-40715781061a.png)
