### ISSUE TITLE
Version 8.2 : Cluster vs Aggregated mode : Bug optimization stops running in Cluster mode 

### ISSUE THREAD

**Issue by eromano2016** [AntaresSimulatorTeam/Antares_Simulator#644]
**Description**
When the stochastic generation of timeseries is activated for the Wind and the Solar in Aggregated mode, the calculation in cluster mode crashes. 

Consequently, one needs to switch to Ready-made timeseries in the aggregated mode in order to starts without any problem in cluster mode.

**How to Reproduce**
See the bug_demo.zip file for an example. 
**Expected behavior**

**Screenshots and additional files**
See bug_demo.zip file

**OS and version**
 - Windows 
 - Antares Simulator version: 8.2

**Additional context**
[Bug_demo.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8487044/Bug_demo.zip)

**Comment by flomnes** [comment]
Thank you for reporting this bug.

@guilpier-code is working on this, he confirmed this crash. The crash is related to output variables.
