### ISSUE TITLE
Must-run thermal clusters ignored in binding constraints

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#649]
Current behavior : ignored
`3 x (cluster) + 2 x (must-run cluster) < rhs`
Expected behavior : move to RHS
`3 x (cluster) < rhs - 2 x (must-run cluster)`

**Comment by guilpier-code** [comment]
To handle this work, a few steps should be taken into account : 
- Supply the class **BindingConstraint** (see **src\libs\antares\study\constraint\constraint.h**) with informations on must-run thermal clusters (weights and offsets). For this we can either : 
    - add 2 more maps to the previous class : **pClusterMustRunWeights** and **pClusterMustRunOffsets**. These would be of type ```std::map<ThermalCluster*, double>```, where the **double** is a **weight** or an **offset**.
    - Or we supply the existing maps (**pClusterWeights** and **pClusterOffsets**) with must-run clusters just like any cluster, and we use the cluster status **cluster->mustrun** to distinguish must-run clusters from the others.
  
Then we'll have to make use of the new data inside and outside the class.

- Handling must-run clusters inside the graphical representation of binding constraints in the GUI.
We add an **\*** symbol after a term related to a must-run cluster in a binding constraint.
See **src\libs\antares\study\constraint\constraint.cpp**, method **buildFormula(...)**

**Comment by pet-mit** [comment]
ANT-2140
