### ISSUE TITLE
Mode expansion : preventing optimization's step 1 from running 

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#673]
When the mode Expansion is activated, Antares Simulator don't run the full optimization : 
- It runs the optimization's step 1
- prints the optimization's step 1 into MPS format
- skips the optimization's step 2

Running optimization's step 1 seems to be useless. In such a case, we should remove it.

Furthermore, Expansion mode seems to affect bounds and RHS of the optimization problem, but only if `reserveJm1 && exp && opt2` is **true**. As `opt2 `is a flag that means we're on optimization step 2, `exp && opt2` is probably always **false**.
This would imply that Expansion mode is useless when setting bounds and RHS of the optimization problem.
See files : 
- src\solver\optimisation\opt_gestion_second_membre_cas_lineaire.cpp : 164
- src\solver\optimisation\opt_gestion_des_bornes_cas_lineaire.cpp : 362

**Comment by flomnes** [comment]
Unfortunately, it is still necessary to run step 1 for hydraulic reservoir levels.

For example, the 2nd week requires the initial water level of each reservoir to be known. It is derived from the final level of the 1st week.
