### ISSUE TITLE
How are binding constraints involving thermal clusters handled in adequacy mode?

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#691]
In the adequacy mode, all thermal clusters are considered as being fully in must-run. As a consequence, it seems that all thermal clusters are removed from the binding constraints (and in particular, binding constraints involving only thermal clusters are disabled).
Can this behavior be confirmed?

**Comment by flomnes** [comment]
Confirmed : I designed a study with an infeasible binding constraint in economy mode. The infeasibility disappears in adequacy mode, indicating that thermal clusters are excluded from BCs in adequacy mode.
