### ISSUE TITLE
OR-Tools : dynamic linking

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#692]
Currently, OR-Tools is statically linked into antares-solver. Making this link dynamic would allow us to de-couple solvers (Sirius, XPRESS, etc.) from Antares. Antares would use whatever solver is available in the libortools.so/libortools.dll dynamic library file.

Investigate feasibility in Windows.

CentOS + Ubuntu : need to break cyclic dependency, no other difficulty is planned.

**Comment by a-zakir** [comment]
Ah this & #1739 are opposites
