### ISSUE TITLE
Problème de répartition du crédit de turbinage (H700-06)

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#695]
**Description du cas**
Cas de test H700-06 (également en PJ)
Système à un nœud doté d'un réservoir géré sans reservoir management, avec des apports un mois sur deux.

**Description du problème**
Lorsque l'étude est lancée en V8.2.1 "vanilla", le réservoir ne turbine que les mois où des apports arrivent dans le réservoir, et la somme du H. STOR chaque mois est égale à la somme des apports (comportement attendu). Plus précisément, sur une semaine à cheval entre un mois avec apports et un mois sans apports, Antares n'autorise dans cette version le réservoir à turbiner que sur les jours de la semaine inclus dans le mois avec apports.

Lorsque l'étude est lancée en V8.2.1 avec patch hydraulique, le réservoir turbine également les mois sans apports. Plus précisément, sur une semaine à cheval entre un mois avec apports et un mois sans apports, Antares autorise dans cette version le réservoir à turbiner chaque jour de la semaine, que ce jour soit inclus dans le mois avec apports ou dans le mois sans apports.

**Lien vers l'étude**
[H700-06_821.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8805462/H700-06_821.zip)

**Comment by flomnes** [comment]
Le comportement est rétabli après application du patch du 1er juin : turbinage non-nul seulement les jours des mois impairs.
