### ISSUE TITLE
Non-respect de la contrainte d'intra-daily modulation (H700-08)

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#696]
**Description du cas**
Cas de test H700-08 (également en PJ)
Système à un nœud doté d'un réservoir géré avec reservoir management, avec des apports uniformes sur l'année.

**Description du problème**
Le paramètre d'intra-daily modulation du réservoir (égal à 1) n'est pas respecté avec le patch hydraulique.
Lorsque l'étude est lancée en V8.2.1 "vanilla", le turbinage du réservoir est uniformisé sur chaque jour, et respecte la contrainte : Puissance turbinée <= intra-daily modulation / 24 * crédit journalier de turbinage.
Lorsque l'étude est lancée en V8.2.1 avec patch, le turbinage du réservoir ne respecte pas cette contrainte ; en pratique, le réservoir turbine à Pmax sur certaines heures, et ne turbine pas sur d'autres heures.
Il est à noter que l'énergie turbinée par semaine est identique avec et sans patch.

**Lien vers l'étude**
[H700-08_821.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8806512/H700-08_821.zip)

**Comment by PPlessiez** [comment]
Le comportement opposé semble se manifester sur l'étude H700-15, dans laquelle l'intra-daily modulation est fixée à 24 :
- En V8.2.1 vanilla, la puissance de turbinage semble capée par la Pmax du réservoir, ce qui est le comportement attendu (pas de limitation due à l'intra-daily modulation)
- En V8.2.1 avec patch, la puissance de turbinage semble limitée au crédit de turbinage journalier / 24 (ce qui serait le comportement attendu si l'intra-daily modulation était fixée à 1).

Lien de l'étude : [H700-15_821.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8807365/H700-15_821.zip)

**Comment by flomnes** [comment]
Après application du correctif du 1er juin, les sorties sont conformes aux attentes, à savoir:

- all weekly hydro generation = 50 GWh, 
- hourly power = from 500 to 2000   from  Monday to Tuesday, average value = 50000/48 MW 
- Note : expected output is 0 MW from Wednesday to Sunday because of the "intra-daily modulation" pararemeter
