### ISSUE TITLE
allow multiple time series for other res & other non res per area in antares

### ISSUE THREAD

**Issue by jorritvm** [AntaresSimulatorTeam/Antares_Simulator#7]
Currently the user can set 1 timeseries for other res & other non res per area. We have however created temperature (and hence climate year) dependant series for these production categories (e.g. CHP's have a negative temperature correlation as more heating is required when it's cold). 

Currently we have to model this using virtual area's where it is inserted as 'solar' & wind production. It would be better to have separate input categories in each antares area. Is it possible to incorporate this into the antares development roadmap?

**Comment by flomnes** [comment]
Dear @jorritvm, this feature was added to Antares Simulator 8.1.0 under the name "renewable generation". Please feel free to check it out !
