### ISSUE TITLE
The displayed sum of cells is incorrect

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#722]
**Description**
In the attached study, when looking at the hydro reservoir inflows Time-Series and selecting the whole TS-1 column, the correct sum of all the inflows is 2600000 MWh.
However, the "Sum" element in the bottom right corner of Antares displays twice this value (5200000 MWh).
It is to be noted that when all the cells of the column are selected except the last one, the sum displayed in Antares is correct.

**Screenshots and additional files**
[H700-20_821.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/8918439/H700-20_821.zip)

**OS and version**
 - OS: Windows 7
 - Antares Simulator version: 8.2.1 (apparently already existing in V8.0.4).

**Comment by guilpier-code** [comment]
I gave a look to that issue.
I can reproduce the problem on my machine with Antares Simulator versions v8.0.4 and v8.2.1 from CI (installer or zipped binaries).
But I can't reproduce the bug when building these versions (v8.0.4 or v8.2.1) on my machine, whether in debug or release mode. 
Note that my Visual studio is 2019 (16.4.0 to be precise), that the visual studio used on github is more recent, and that it could explain the difference of behavior.
@flomnes : what about Ubuntu ?

**Comment by flomnes** [comment]
@guilpier-code Can't reproduce on Ubuntu, since only the Cell Number is displayed, sometimes with a lag, sometimes not at all.

@PPlessiez Confirms that this bug affects v8.3.0
