### ISSUE TITLE
interco***.txt file deleted

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/Antares_Simulator#728]
Hello,
**Description**
interco**.txt file is used by `lp_namer` step of `antares-xpansion`, after some tests with `antares 8.3-rc1` it seems that interco file is not produced. In fact the file is created and deleted in runtime.
see 
![interco](https://user-images.githubusercontent.com/32519851/175572390-e193d880-8c69-4763-806a-b19c4eb801fa.PNG)

**How to Reproduce**
normal run of antares in *economy mode* and `include-exportmps = true
include-exportstructure = true`

**Comment by flomnes** [comment]
Only `interco-1-1.txt` is created. Is it not enough ? I don't think you'd need one for each week, right ?

interco-1-1.txt is only created at the 1st week of the simulation
```cpp
void OPT_ExportInterco(const Antares::Data::Study& study,
                       PROBLEME_HEBDO* ProblemeHebdo,
                       uint numSpace)
{
    // Interco are exported only once for first year
    if (ProblemeHebdo->firstWeekOfSimulation)
    {
    // ...
    }
}
```

**Comment by a-zakir** [comment]
sorry, after checks, the problem come from the way xpansion cleans files after antares step, since files naming has changed with antares8.3-rc1 it appears that files ending with `-1.txt` or `-1.mps` are automatically removed.  These files were considered useless. 
in `antares-xpansion/src/python/antares_xpansion/study_output_cleaner.py`
`class StudyOutputCleaner:

    @staticmethod
    def clean_antares_step(study_output: Path):
        remove_files_containing_str_from_dir('-1.mps', study_output)
        remove_files_containing_str_from_dir('criterion', study_output)
        remove_files_containing_str_from_dir('-1.txt', study_output)`
