### ISSUE TITLE
Expansion mode and include-exportsmps option

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/Antares_Simulator#729]
**Description**
Antares 8.3 come with possibility to split mps file into fixed and variables part.
In Expansion mode of antares 8.3-rc1 along with `include-exportsmps ` setted to true, it seems that the fixed part (i.e problem-fixed-part-1-1.mps file) is created and deleted in runtime. 

below capture of antares running
![fixed_part1](https://user-images.githubusercontent.com/32519851/175576579-78c13075-fcb1-4060-82da-c4d501744d7e.PNG)

after antares ended:
![fixed_part_deleted](https://user-images.githubusercontent.com/32519851/175576577-5958e054-512a-411e-ad74-dd12f25d44da.PNG)

**Comment by flomnes** [comment]
~~I was able to reproduce with v8.3.0-rc1.~~

My bad, I didn't use the Expansion study mode. Can't reproduce.

**Comment by flomnes** [comment]
@a-zakir Can you post a zip containing the study ?

Will include in v8.3.1, since no release of xpansion is expected anytime soon.

**Comment by a-zakir** [comment]
same issue as #728
