### ISSUE TITLE
GUI freezes on SAVE / RUN

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#737]
On a big study (155 areas, 479 links)  :

- release version "antares-8.3.0-rc1-Ubuntu-20.04.deb" - stuck at SAVE. Upon close/open stuck at RUN.
- release version "antares-8.2.2-Ubuntu-20.04.deb" - stuck at SAVE. Upon close/open stuck at RUN.
- release version "antares-8.2.1-Ubuntu-20.04.deb" - works FINE!
- develop versions we have - stuck at SAVE. Upon close/open stuck at RUN.

**Comment by flomnes** [comment]
Was not able to reproduce.

From the git history, this freeze is probably caused by  #658, since it is the only commit related to the GUI between v8.2.1 and v8.2.2.

**Comment by guilpier-code** [comment]
We fixed this in the pull request #721.
This bug occurs when the study's map contains several layers : we have an infinite loop over the layers.
This bug was introduced when removing warnings.
It is ok now with the most recent commits of branch **develop**

**Comment by flomnes** [comment]
@guilpier-code This could be that. However, I'd be surprised since #721 was shipped into v8.3.0-rc1, and yet @hugo-antoine-rtei was able to reproduce on v8.3.0-rc1.

We should ask the initial reporter to reproduce on v8.3.0-rc1.

**Comment by guilpier-code** [comment]
I agree, PR #721 may not fix this issue eventually.
We need a crashing study to investigate further.
