### ISSUE TITLE
[Antares V8.3.0 - RC2] The copy-paste of areas freezes the GUI

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#773]
**Description**
When the user copy-pastes an area using the GUI (see example in attached study), the copy-pasting pop-up is displayed but it freezes and cannot be closed by the user.

**Expected behavior**
The pop-up should close after the copy-paste is completed and the area should be correctly duplicated.

**Screenshots and additional files**
[profit_by_cluster_github.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9091293/profit_by_cluster_github.zip)
![freeze_area_copy](https://user-images.githubusercontent.com/53614116/178451749-17fa1a88-205b-4bc6-aaea-bffaef95e5ec.png)

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.3.0 - RC2

**Comment by flomnes** [comment]
There is already an issue, will close this one.

Fix #550 seems to be related.

**Comment by flomnes** [comment]
Issue #734
