### ISSUE TITLE
Simulation cores parameter doesn't work without saving

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [AntaresSimulatorTeam/Antares_Simulator#789]
**Description**
Changing the "Simulation cores" parameter inside the Advanced parameters window, is not taken into account when running the study, if you don't save the study.

**How to Reproduce**
- Create an empty study with "minimum" as "Simulation cores"
- Add one area
- Save the study
- Click "Run a simulation", select parallel, the screen prints Simulation cores: 1 as expected
- Change "Simulation cores" to "maximum" in the Advanced parameters
- Click "Run a simulation", select parallel, the screen still prints Simulation cores: 1 <- it depends on your system but it should be higher

**Expected behavior**
Either we should get a prompt to save the study before running it, this would solve this issue as when you save the study, the correct number of simulation cores will be displayed in the "Run simulation window". Or, the number of simulation cores should dynamically evolve with the option chosen.

**OS and version**
 - OS: reported to me on Windows, reproduced on Ubuntu
 - Antares Simulator version: reported on to me on 8.0.4, reproduced on 8.3.0

**Comment by flomnes** [comment]
@hugo-antoine-rtei Do you get the right level of parallelism if you save the study before running the simulation ?

**Comment by hugo-antoine-rtei** [comment]
yes I do

**Comment by flomnes** [comment]
Ok, the UI should force you to save the study if you modified it before running it. I'll investigate.
