### ISSUE TITLE
Renewable cluster in version 8.2 is missing in districts aggregation

### ISSUE THREAD

**Issue by eromano2016** [AntaresSimulatorTeam/Antares_Simulator#800]
In an Antares 8,2 study, I  have defined an area with renewable clusters. The cluster has 2 groups (PV and Wind).  
In parallel, I also defined a district which  includes this area in the district set. 

 While, the renewables generation correctly appears in the output of the area (see Area view), it fails to  appear as an output in the districts output (dsitrict view). 

Is this related to a bug, or am I missing something ? 

Best

E.Romano
![Area_view](https://user-images.githubusercontent.com/21000377/183080894-a36b7be2-3d46-4835-a23f-d095abfecaeb.png)
![district_view](https://user-images.githubusercontent.com/21000377/183080920-b527f0dc-43f3-45b8-b421-c376673ba238.png)

**Comment by eromano2016** [comment]
The problem also appears in version 8.3

**Comment by flomnes** [comment]
Thanks @eromano2016 for your feedback. This is indeed a bug, it will be fixed in the next release.

**Comment by flomnes** [comment]
~~Note that newly added columns are also missing from districts (DENS, etc.).~~
