### ISSUE TITLE
Sirius+OR-Tools broken

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#831]
**Description**
The resolution fails with the following log message
> W0824 16:30:31.346637 732164 sirius_interface.cc:1069] SetPrimalTolerance not implemented for sirius_interface
> W0824 16:30:31.346658 732164 sirius_interface.cc:1074] SetDualTolerance not implemented for sirius_interface

**How to Reproduce**
Get the 2 attached studies and run them both. One fails (on first week), the others succeeds.

**Command** : 
> antares-8.3-solver <path/to/study> --use-ortools --ortools-solver sirius

**Expected behavior**
The resolution should succeed.

**OS and version**
 - OS: Ubuntu 20.04
 - Antares Simulator version: 8.3.1

**Additional context**
OR-Tools 9.2-rte1.3

**Studies for tests**
[021 Four areas - DC law - 7days.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9972343/021.Four.areas.-.DC.law.-.7days.zip) (Fails)
[bc-marginal-price.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9972348/bc-marginal-price.zip) (succeeds)

**Comment by guilpier-code** [comment]
This issue is closed because replaced by #936
