### ISSUE TITLE
Links : separate UI and properties

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#85]
A typical `properties.ini` for a link looks like this

```
[target_node]
hurdles-cost = false
loop-flow = false
use-phase-shifter = false
transmission-capacities = enabled
asset-type = ac
link-style = plain
link-width = 1
colorr = 112
colorg = 112
colorb = 112
display-comments = true
filter-synthesis = hourly, daily, weekly, monthly, annual
filter-year-by-year = hourly, daily, weekly, monthly, annual
```

**Proposal** : Separate UI elements from technical elements.

UI elements :
- link-style = plain
- link-width = 1
- colorr = 112
- colorg = 112
- colorb = 112
- display-comments = true

Technical elements :
- hurdles-cost = false
- loop-flow = false
- use-phase-shifter = false
- transmission-capacities = enabled
- asset-type = ac
- filter-synthesis = hourly, daily, weekly, monthly, annual
- filter-year-by-year = hourly, daily, weekly, monthly, annual

**Comment by sgatto** [comment]
Leads to incompatibilities, not fixing
