### ISSUE TITLE
criterion.txt unused

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#857]
Don't write it.

Remove function `OPT_EcrireResultatFonctionObjectiveAuFormatTXT` and all calls to it.

**Comment by guilpier-code** [comment]
**criterion.txt** can be a quick and convenient way to check : 
- for regressions : if a change in the code produces a different objective function value, then there is a regression.
- that a change in the code causes an equivalent solution of the weekly (optimization) problem  or not
