### ISSUE TITLE
What is mode Xpansion ? When should it be used ?

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#858]
Notable differences
**src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp**, some changes in function `OPT_AjusterLeNombreMinDeGroupesDemarresCoutsDeDemarrage`.

In file **src/solver/optimisation/opt_optimisation_lineaire.cpp**, only one resolution is done if this mode is enabled (not 2)
```cpp
if (ProblemeHebdo->Expansion == NON_ANTARES)
    goto OptimisationHebdo;
```
Day-ahead reserves (**solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp**:162, 
**solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp**:363), but it's dead code since `exp && opt2` should always evaluate to `false` (see above).

**Comment by flomnes** [comment]
Xpansion only needs MPS files. Create a command-line parameter to disable resolutions and produce MPS files only ?

**Comment by a-zakir** [comment]
Besoin de plus d’infos

**Comment by pet-mit** [comment]
ANT-2188
