### ISSUE TITLE
The copy-paste option doesn't work for renewable clusters

### ISSUE THREAD

**Issue by matijaosmosian** [AntaresSimulatorTeam/Antares_Simulator#871]
**Description**
Renewable clusters are missing inside area copied from an existing area (within the same model or from one model to the another).

**How to Reproduce**
1. Open a new ANTARES study
2. Create ANTARES area with one renewable cluster and one thermal cluster for instance.
3. Copy and paste the area (to area-2).
4. Go to area-2 and "Renewable" tab
5. Check if renewable cluster is missing
6. Go to "Thermal" tab and realize that thermal cluster is present.

**Expected behavior**
It is expected that renewable cluster should be copied from the original area in the same way as thermal, load, etc.

**Screenshots and additional files**
![image](https://user-images.githubusercontent.com/77788527/191036603-beccc63e-086e-4df0-8b15-19ee50ff0e98.png)

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.3.1

**Additional context**

**Comment by flomnes** [comment]
Thank you for reporting the issue. However, we're planning to discontinue the development of the current Desktop GUI (as shown above). It will be replaced shortly by Antares Web, see https://github.com/AntaresSimulatorTeam/AntaREST. This new GUI will come with a better UX and more features.

We already spotted issues with the copy/paste feature. Fixing these issues would take about 3 weeks of development. We won't fix this issue, sorry.

**Comment by matijaosmosian** [comment]
Dear Florian,

 

Thank you for the information.

 

Best regards,

Matija
