### ISSUE TITLE
Make generatdata.ini file complient for "playlist" keys

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/Antares_Simulator#889]
Currently generaldata.ini host a "playlist" section. This section contains repeated lines looking like `playlist + = 0` with "0" being any number value.

The repetition of the same key `playlist +` is non compliant with most ini reader (e.g. ConfigReader, default python ini parser)

Being compliant with "standard" reader remove the need for in house reader and writer of ini files in Simulator and Xpansion.

Here a python example:

```
def test_read_playlist(self, tmp_path):
  settings_dir = TestGeneralDataProcessor.get_settings_dir(tmp_path)
  settings_dir.mkdir()
  gen_data_path = settings_dir / self.generaldata_filename
  with open(gen_data_path, "w") as writer:
      writer.write("[playlist]\n")
      writer.write("playlist_year =0, 42\n")
  actual_config = configparser.ConfigParser()
  actual_config.read(gen_data_path)
  assert [int(year.strip()) for year in actual_config.get("playlist", "playlist_year").split(',')] == [0, 42]
```

**Comment by a-zakir** [comment]
Works fine
