### ISSUE TITLE
Oracle8 CI : use ccache + docker volume persistency

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#890]
Since the build is set up within a docker image, persistence is a bit tricky.

However, mounting volumes allows persistence of data.

General idea https://stackoverflow.com/questions/39650056/using-ccache-when-building-inside-of-docker

Github workflow configuration https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

The only missing part seems to be the download/upload of cache data.

**Comment by pet-mit** [comment]
ANT-2175
