### ISSUE TITLE
[Antares V8.3.2] Thermal time-series generation not working for must-run clusters

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#908]
**Description**
For clusters in full must-run ("must-run" parameter set to "True"), the generation of thermal availability time-series does not work: even if the global parameter is set to "stochastic TS" for thermal, no TS is generated for these clusters.

**How to Reproduce**
Create a cluster, set "must-run" to True, populate the TS generation parameters, and try to generate TS for this cluster.

**Expected behavior**
TS generation should work for clusters in must-run just as it works for dispatchable clusters.

**Screenshots and additional files**
Example study with one cluster
[Case study result_V8.3.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9766918/Case.study.result_V8.3.zip)

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.3.2

**Comment by PPlessiez** [comment]
This issue was still witnessed in Antares V8.5

**Comment by flomnes** [comment]
EDIT : Could not reproduce

See `simulationObj->prepareClustersInMustRunMode(numSpace);`

This removes must-run clusters from `PartThermal::list`, adds to `PartThermal::mustrunList`

Then in **src/solver/ts-generator/thermal.cpp**, we only generate TS for clusters which are in `PartThermal::list`. We could also generate TS for those in `PartThermal::mustrunList` (both are in `PartThermal::clusters`)

**Comment by flomnes** [comment]
@PPlessiez Could not reproduce with v8.6-rc4

**Comment by flomnes** [comment]
@PPlessiez Could not reproduce with v8.5.0
