### ISSUE TITLE
[Antares V8.3.2] Binding constraints synthetic results not exported

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#918]
**Description**
The attached study contains a number of binding constraints for which the parameter "filter-synthesis" is set to "hourly, daily, weekly, monthly, annual". But when the simulation is run, the "mc-all/binding_constraints" folder of the output does not contain any file.

**How to Reproduce**
Execute the attached study on one MC Year.

**Expected behavior**
The "mc-all/binding_constraints" folder of the output should contain text files corresponding to the prices of the constraints at the granularities set in the "filter-synthesis" parameters.

**Screenshots and additional files**
Download study using the following link: https://postngo.rte-france.com/?lang=fr&a=d&i=iEHrnwmIbU2AmXVMk0CF 

**OS and version**
 - OS: Windows
 - Antares Simulator version: V8.3.2

**Comment by flomnes** [comment]
Duplicate, see #912
