### ISSUE TITLE
TS-numbers pour les liens scénarisés et tirés aléatoirement

### ISSUE THREAD

**Issue by JMJ-rte** [AntaresSimulatorTeam/Antares_Simulator#925]
**Description**
Lorsqu'on a un lien scénarisé et qu'on a choisi un tirage aléatoire du numéro de TS pour chacun des scénarios, on peut en mettant à "TRUE" le paramètre "MC scenarios" récupérer pour ces liens le résultat des tirage aléatoire sous forme d'un vecteur qui a chaque scénario MC associe un numéro de TS.
Toutefois ce vecteur ne semble pas correctement enregistré si on ne demande pas simultanément des sorties "year-by-year" du lien correspondant 

**How to Reproduce**
Pour reproduire l'anomalie, il faut lancer une version Antares au moins égale à la V8.2, version à partir de laquelle les liens sont scénarisables. 
Sélectionner un lien et y mettre au moins 2 times series.
Dans "MC scenario builder" forcer à "rand" la sélection de la TS pour ce lien. 
Ne pas demander la sortie "year-by-year" de ce lien (ou de tous les liens). 
Editer le fichier "TS-numbers/NTC/Noeud amont/Noeud-amont/Noeud-aval.txt".
Constater que ce fichier ne contient pas un panachage de "1" et de "2", mais que des "1"

**Expected behavior**
Indépendamment du choix de récupérer ou non les sorties d'un lien, la chronique de numéro de TS enregistrée doit être correcte. 

**Screenshots and additional files**
RAS

**OS and version**
 - OS: Windows, 
 - Antares Simulator version: 8.2 ou 8.3

**Additional context**
RAS

**Comment by guilpier-code** [comment]
Sur l'étude en PJ, on n'arrive pas à reproduire l'anomalie décrite, bien que sa configuration soit conforme à la rubrique  **How to Reproduce** ci-dessus.
Noter que le lien EAST->NORTH possède 2 séries temporelles en NTC et que le rapport **ts-numbers/ntc/east/north.txt** contient : 

size:1x5
1
2
2
2
2

Le test a été fait avec la v8.3.1 officielle.

Etude en PJ : 
[021 Four areas - DC law - 8.3.1.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9881008/021.Four.areas.-.DC.law.-.8.3.1.zip)

**Comment by flomnes** [comment]
Par réussi à reproduire en 8.2.0 ni en 8.3.2

**Comment by guilpier-code** [comment]
Tentative de reproduction de l'anomalie avec l'équipe script R (consortia) sur l'étude sur laquelle l'anomalie a été constatée : échec
Ce ticket doit être fermé.
