### ISSUE TITLE
Debug mode on Windows leads to crashes

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#932]
Debug mode on Windows leads to unpredictable and inexplicable crashes on running any study.

**Comment by flomnes** [comment]
@guilpier-code Is it still the case ?

**Comment by guilpier-code** [comment]
I don't know, due to this issue, I don't use the debug mode anymore

**Comment by guilpier-code** [comment]
> @guilpier-code Is it still the case ?

I don't know : due to this issue, I don't use the debug mode anymore

**Comment by a-zakir** [comment]
linked  #1673
