### ISSUE TITLE
RHS file is invalid for weekly, daily binding constraints

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#941]
The file contains only 1 column, solver expects 3 (but only uses one)
```
study/input/bindingconstraints/new binding constraint.txt: at line 1, not enough columns (expected 3, got 1)
study/input/bindingconstraints/new binding constraint.txt: at line 2, not enough columns (expected 3, got 1)
study/input/bindingconstraints/new binding constraint.txt: at line 3, not enough columns (expected 3, got 1)
study/input/bindingconstraints/new binding constraint.txt: at line 4, not enough columns (expected 3, got 1)
study/input/bindingconstraints/new binding constraint.txt: at line 5, not enough columns (expected 3, got 1)
study/input/bindingconstraints/new binding constraint.txt: at line 6, not enough columns (expected 3, got 1)
Found 7 warnings: The simulation must stop.
Aborting now. See logs for more details
```

This does not happen for hourly binding constraints.

Reproducible with v8.3.2, possibly earlier versions as well.

**Comment by guilpier-code** [comment]
What do you do to get to this situation ?

**Comment by flomnes** [comment]
> What do you do to get to this situation ?

1. Create a new study in the GUI
2. Create two areas, and a link between them
3. Create a weekly / daily binding constraint
4. Set the coefficient of the link to "1" in the binding constraint
5. Set a non-zero coefficient as the RHS in the binding constraints (matrices with 0 coeffs are saved as an empty file, for which the solver runs OK)
6. Examine the file **input/bindingconstraints/<constraint>.txt**, it should have 3 columns but only has 1.

**Comment by guilpier-code** [comment]
As you can see, I don't have the problem you point. I can't reproduce it.
[one-bc-daily.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9981621/one-bc-daily.zip)

Would this problem occur only on Linux Ubuntu ?

**Comment by flomnes** [comment]
@guilpier-code Indeed, I could not reproduce with **daily** binding constraints. This bug only occurs with **weekly** binding constraints. Can you try this ?

**Comment by guilpier-code** [comment]
I tried with a **weekly** binding constraint on an official **v8.3.2**, I still can't reproduce the bug, sorry.
I also tried with the current **develop** : same result, no can do.

**Comment by flomnes** [comment]
OK this seems to be a Linux-only issue, I will close it.
