### ISSUE TITLE
Compile with clang/llvm

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#951]
- Yuni defines weird compile flags, we'll need to clean them up
- It is impossible to build the project in Mac OS, since it uses clang
- Compare build/execution time

**Comment by payetvin** [comment]
To use clang:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
Then build in a new folder

Yuni compilation errors:
src/ext/yuni/src/yuni/core/event/../../core/string/iterator.inc.hpp:192:27: error: use of overloaded operator '!=' is ambiguous (with operand types 'UTF8::Char' and 'const char')
src/ext/yuni/src/yuni/uuid/../core/system/stdint.h:141:2: error: expected ';' after struct} __float128

They're either probably flag errors, or real code problem. Clang is stricter then gcc for some type comparison
https://stackoverflow.com/questions/25745759/clang-vs-gcc-vs-msvc-template-conversion-operator-which-compiler-is-right/25758367#25758367
https://stackoverflow.com/questions/25110429/ambiguous-operator-overload-on-clang
