### ISSUE TITLE
Ortools-sirius and MPS problems

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#96]
Asking MPS problems generation in the study and running Antares with sirius behind orTools does not print MPS problems.
When a resolution with sirius only is asked, MPS problems are printed.

**Comment by jmkerloch** [comment]
When using OR-Tools, MPS are written with OR-Tools object `MPSolver::Write `method.

This method use `SiriusInterface::Write` method : 

```
void SiriusInterface::Write(const std::string& filename) {
		if (sync_status_ == MUST_RELOAD) {
			Reset();
		}
		ExtractModel();
		VLOG(1) << "Writing Sirius MPS \"" << filename << "\".";
		const int status = SRSwritempsprob(mLp->problem_mps, filename.c_str());
		if (status) {
			LOG(WARNING) << "Failed to write MPS.";
		}
	}
```

This should work but the method `SRSwritempsprob `does nothing in sirius : 

```
int SRSwritempsprob(PROBLEME_MPS * problem_mps, const char * fileName) {
	PROBLEME_A_RESOUDRE problem_a_resoudre;
	PROBLEME_PNE problem_pne;
	PNE_copy_problem(problem_mps, &problem_a_resoudre, 0, 0.0);
	//FIXME PNE_EcrireJeuDeDonneesMPS_avecNom(&problem_pne, &problem_a_resoudre, fileName);

	return 0;
}
```

**Comment by flomnes** [comment]
This issue is still valid. Move the MPS writing function from Antares to Sirius Solver. 

@klorel can we offer a fix for this in Sirius ?
