### ISSUE TITLE
Exporting results : binding constraints takes time, even when not needed

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#965]
How to reproduce

1. Take a large study containing hundreds of binding constraints
2. Disable all outputs for binding constraints
3. Run a simulation
4. The following step appears in the logs and takes ~1 min
```
Exporting results : binding constraints
```
I suspect it's the synthesis export for all binding constraints. The study also has 1000 MC years, with only 12 enabled.

There must be a large loop that looks like this
```cpp
for (auto& year : allYears) {
   for (auto& bc : bindingConstraints) {
      // do stuff
   }
}
```
The problem is that step is completely unnecessary, because the user doesn't expect any results for binding constraints. This is a clear violation of the "pay for what you use" principle.

**Comment by guilpier-code** [comment]
Could not reproduce the slowness.
It still takes a few seconds (between 3 and 10 seconds, more often 4) per year to build annual results by aggregation regarding the **binding constraints** results : 
- when the study contains many **BC**s (315 in the study I had).
- when user deactivate the output of marginal costs on **BC**s 

So this overhead is not a big deal.
However, we should still consider not computing these results at any time intervals when marginal costs on **BC**s is not asked by user.
This works a well for any other output variables.
