### ISSUE TITLE
Sirius behind ortools : regressions

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#99]
Running sirius behind ortools causes regression in regard to running sirius alone.
For a given study :
- Results files can be different (though differences are tiny)
- checkIntegrity.txt files can be different as well, but more rarely. Most of the time they are equal.
- Time duration of a study are often quite different : running sirius behind ortools is much slower, up to 3 times the duration when running the same study with sirius alone.

**Comment by guilpier-code** [comment]
- The problem of the time durations comes from the optimization problem resolution.
It is not caused by the previous step : conversion of the optimization problem into a ortools problem. Indeed, some time measurement were done that

**Comment by flomnes** [comment]
> It is possible that solving the time durations issue by activating hot start correctly in ortools-sirius makes all regressions disappear.

You were right ! We'll need to check that this regression is fixed for the upcoming release 8.1.1
